/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta API
 * Allta API 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AppleLoginCallbackRequest,
  FindUserBySocialIdRequest,
  FindUserBySocialIdResponse,
  GetNewAccessTokenRequest,
  LoginBySocialIdRequest,
  UserLogoutRequest
} from '.././models';

import { customInstance } from '../../libs/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const authControllerKakaoLoginCallback = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/auth/kakao`, method: 'GET', signal
    },
      options);
    }
  



export const getAuthControllerKakaoLoginCallbackQueryKey = () => {
    return [
    `/auth/kakao`
    ] as const;
    }

    
export const getAuthControllerKakaoLoginCallbackQueryOptions = <TData = Awaited<ReturnType<typeof authControllerKakaoLoginCallback>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerKakaoLoginCallback>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAuthControllerKakaoLoginCallbackQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof authControllerKakaoLoginCallback>>> = ({ signal }) => authControllerKakaoLoginCallback(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof authControllerKakaoLoginCallback>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AuthControllerKakaoLoginCallbackQueryResult = NonNullable<Awaited<ReturnType<typeof authControllerKakaoLoginCallback>>>
export type AuthControllerKakaoLoginCallbackQueryError = unknown


export function useAuthControllerKakaoLoginCallback<TData = Awaited<ReturnType<typeof authControllerKakaoLoginCallback>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerKakaoLoginCallback>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof authControllerKakaoLoginCallback>>,
          TError,
          Awaited<ReturnType<typeof authControllerKakaoLoginCallback>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuthControllerKakaoLoginCallback<TData = Awaited<ReturnType<typeof authControllerKakaoLoginCallback>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerKakaoLoginCallback>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof authControllerKakaoLoginCallback>>,
          TError,
          Awaited<ReturnType<typeof authControllerKakaoLoginCallback>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuthControllerKakaoLoginCallback<TData = Awaited<ReturnType<typeof authControllerKakaoLoginCallback>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerKakaoLoginCallback>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useAuthControllerKakaoLoginCallback<TData = Awaited<ReturnType<typeof authControllerKakaoLoginCallback>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerKakaoLoginCallback>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAuthControllerKakaoLoginCallbackQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const authControllerGoogleLoginCallback = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/auth/google`, method: 'GET', signal
    },
      options);
    }
  



export const getAuthControllerGoogleLoginCallbackQueryKey = () => {
    return [
    `/auth/google`
    ] as const;
    }

    
export const getAuthControllerGoogleLoginCallbackQueryOptions = <TData = Awaited<ReturnType<typeof authControllerGoogleLoginCallback>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerGoogleLoginCallback>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAuthControllerGoogleLoginCallbackQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof authControllerGoogleLoginCallback>>> = ({ signal }) => authControllerGoogleLoginCallback(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof authControllerGoogleLoginCallback>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AuthControllerGoogleLoginCallbackQueryResult = NonNullable<Awaited<ReturnType<typeof authControllerGoogleLoginCallback>>>
export type AuthControllerGoogleLoginCallbackQueryError = unknown


export function useAuthControllerGoogleLoginCallback<TData = Awaited<ReturnType<typeof authControllerGoogleLoginCallback>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerGoogleLoginCallback>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof authControllerGoogleLoginCallback>>,
          TError,
          Awaited<ReturnType<typeof authControllerGoogleLoginCallback>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuthControllerGoogleLoginCallback<TData = Awaited<ReturnType<typeof authControllerGoogleLoginCallback>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerGoogleLoginCallback>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof authControllerGoogleLoginCallback>>,
          TError,
          Awaited<ReturnType<typeof authControllerGoogleLoginCallback>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuthControllerGoogleLoginCallback<TData = Awaited<ReturnType<typeof authControllerGoogleLoginCallback>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerGoogleLoginCallback>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useAuthControllerGoogleLoginCallback<TData = Awaited<ReturnType<typeof authControllerGoogleLoginCallback>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerGoogleLoginCallback>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAuthControllerGoogleLoginCallbackQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const authControllerAppleLoginCallback = (
    appleLoginCallbackRequest: AppleLoginCallbackRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/auth/apple`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: appleLoginCallbackRequest, signal
    },
      options);
    }
  


export const getAuthControllerAppleLoginCallbackMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerAppleLoginCallback>>, TError,{data: AppleLoginCallbackRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof authControllerAppleLoginCallback>>, TError,{data: AppleLoginCallbackRequest}, TContext> => {

const mutationKey = ['authControllerAppleLoginCallback'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerAppleLoginCallback>>, {data: AppleLoginCallbackRequest}> = (props) => {
          const {data} = props ?? {};

          return  authControllerAppleLoginCallback(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AuthControllerAppleLoginCallbackMutationResult = NonNullable<Awaited<ReturnType<typeof authControllerAppleLoginCallback>>>
    export type AuthControllerAppleLoginCallbackMutationBody = AppleLoginCallbackRequest
    export type AuthControllerAppleLoginCallbackMutationError = unknown

    export const useAuthControllerAppleLoginCallback = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerAppleLoginCallback>>, TError,{data: AppleLoginCallbackRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authControllerAppleLoginCallback>>,
        TError,
        {data: AppleLoginCallbackRequest},
        TContext
      > => {

      const mutationOptions = getAuthControllerAppleLoginCallbackMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const authControllerFindUserBySocialId = (
    findUserBySocialIdRequest: FindUserBySocialIdRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<FindUserBySocialIdResponse>(
      {url: `/auth/social`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: findUserBySocialIdRequest, signal
    },
      options);
    }
  


export const getAuthControllerFindUserBySocialIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerFindUserBySocialId>>, TError,{data: FindUserBySocialIdRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof authControllerFindUserBySocialId>>, TError,{data: FindUserBySocialIdRequest}, TContext> => {

const mutationKey = ['authControllerFindUserBySocialId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerFindUserBySocialId>>, {data: FindUserBySocialIdRequest}> = (props) => {
          const {data} = props ?? {};

          return  authControllerFindUserBySocialId(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AuthControllerFindUserBySocialIdMutationResult = NonNullable<Awaited<ReturnType<typeof authControllerFindUserBySocialId>>>
    export type AuthControllerFindUserBySocialIdMutationBody = FindUserBySocialIdRequest
    export type AuthControllerFindUserBySocialIdMutationError = unknown

    export const useAuthControllerFindUserBySocialId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerFindUserBySocialId>>, TError,{data: FindUserBySocialIdRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authControllerFindUserBySocialId>>,
        TError,
        {data: FindUserBySocialIdRequest},
        TContext
      > => {

      const mutationOptions = getAuthControllerFindUserBySocialIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const authControllerUserLogout = (
    userLogoutRequest: UserLogoutRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/auth/logout`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: userLogoutRequest, signal
    },
      options);
    }
  


export const getAuthControllerUserLogoutMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerUserLogout>>, TError,{data: UserLogoutRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof authControllerUserLogout>>, TError,{data: UserLogoutRequest}, TContext> => {

const mutationKey = ['authControllerUserLogout'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerUserLogout>>, {data: UserLogoutRequest}> = (props) => {
          const {data} = props ?? {};

          return  authControllerUserLogout(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AuthControllerUserLogoutMutationResult = NonNullable<Awaited<ReturnType<typeof authControllerUserLogout>>>
    export type AuthControllerUserLogoutMutationBody = UserLogoutRequest
    export type AuthControllerUserLogoutMutationError = unknown

    export const useAuthControllerUserLogout = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerUserLogout>>, TError,{data: UserLogoutRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authControllerUserLogout>>,
        TError,
        {data: UserLogoutRequest},
        TContext
      > => {

      const mutationOptions = getAuthControllerUserLogoutMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const authControllerLoginBySocialId = (
    loginBySocialIdRequest: LoginBySocialIdRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/auth/social/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: loginBySocialIdRequest, signal
    },
      options);
    }
  


export const getAuthControllerLoginBySocialIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerLoginBySocialId>>, TError,{data: LoginBySocialIdRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof authControllerLoginBySocialId>>, TError,{data: LoginBySocialIdRequest}, TContext> => {

const mutationKey = ['authControllerLoginBySocialId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerLoginBySocialId>>, {data: LoginBySocialIdRequest}> = (props) => {
          const {data} = props ?? {};

          return  authControllerLoginBySocialId(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AuthControllerLoginBySocialIdMutationResult = NonNullable<Awaited<ReturnType<typeof authControllerLoginBySocialId>>>
    export type AuthControllerLoginBySocialIdMutationBody = LoginBySocialIdRequest
    export type AuthControllerLoginBySocialIdMutationError = unknown

    export const useAuthControllerLoginBySocialId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerLoginBySocialId>>, TError,{data: LoginBySocialIdRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authControllerLoginBySocialId>>,
        TError,
        {data: LoginBySocialIdRequest},
        TContext
      > => {

      const mutationOptions = getAuthControllerLoginBySocialIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const authControllerGetNewUserAccessToken = (
    getNewAccessTokenRequest: GetNewAccessTokenRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/auth/token/refresh`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getNewAccessTokenRequest, signal
    },
      options);
    }
  


export const getAuthControllerGetNewUserAccessTokenMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerGetNewUserAccessToken>>, TError,{data: GetNewAccessTokenRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof authControllerGetNewUserAccessToken>>, TError,{data: GetNewAccessTokenRequest}, TContext> => {

const mutationKey = ['authControllerGetNewUserAccessToken'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerGetNewUserAccessToken>>, {data: GetNewAccessTokenRequest}> = (props) => {
          const {data} = props ?? {};

          return  authControllerGetNewUserAccessToken(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AuthControllerGetNewUserAccessTokenMutationResult = NonNullable<Awaited<ReturnType<typeof authControllerGetNewUserAccessToken>>>
    export type AuthControllerGetNewUserAccessTokenMutationBody = GetNewAccessTokenRequest
    export type AuthControllerGetNewUserAccessTokenMutationError = unknown

    export const useAuthControllerGetNewUserAccessToken = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerGetNewUserAccessToken>>, TError,{data: GetNewAccessTokenRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authControllerGetNewUserAccessToken>>,
        TError,
        {data: GetNewAccessTokenRequest},
        TContext
      > => {

      const mutationOptions = getAuthControllerGetNewUserAccessTokenMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    