/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Allta API
 * Allta의 REST API 문서입니다.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  CheckPhoneNumberExistsDto,
  CheckUserBySocialIdDto,
  LoginBySocialIdDto,
  Response,
  SendVerificationCodeDto,
  VerifyPhoneNumberDto
} from '.././models';

import { customInstance } from '../../libs/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const authControllerCheckUserBySocialId = (
    checkUserBySocialIdDto: CheckUserBySocialIdDto,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<boolean>(
      {url: `/auth/social/check`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: checkUserBySocialIdDto, signal
    },
      options);
    }
  


export const getAuthControllerCheckUserBySocialIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerCheckUserBySocialId>>, TError,{data: CheckUserBySocialIdDto}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof authControllerCheckUserBySocialId>>, TError,{data: CheckUserBySocialIdDto}, TContext> => {

const mutationKey = ['authControllerCheckUserBySocialId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerCheckUserBySocialId>>, {data: CheckUserBySocialIdDto}> = (props) => {
          const {data} = props ?? {};

          return  authControllerCheckUserBySocialId(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AuthControllerCheckUserBySocialIdMutationResult = NonNullable<Awaited<ReturnType<typeof authControllerCheckUserBySocialId>>>
    export type AuthControllerCheckUserBySocialIdMutationBody = CheckUserBySocialIdDto
    export type AuthControllerCheckUserBySocialIdMutationError = unknown

    export const useAuthControllerCheckUserBySocialId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerCheckUserBySocialId>>, TError,{data: CheckUserBySocialIdDto}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authControllerCheckUserBySocialId>>,
        TError,
        {data: CheckUserBySocialIdDto},
        TContext
      > => {

      const mutationOptions = getAuthControllerCheckUserBySocialIdMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    export const authControllerLoginBySocialId = (
    loginBySocialIdDto: LoginBySocialIdDto,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Response>(
      {url: `/auth/social/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: loginBySocialIdDto, signal
    },
      options);
    }
  


export const getAuthControllerLoginBySocialIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerLoginBySocialId>>, TError,{data: LoginBySocialIdDto}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof authControllerLoginBySocialId>>, TError,{data: LoginBySocialIdDto}, TContext> => {

const mutationKey = ['authControllerLoginBySocialId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerLoginBySocialId>>, {data: LoginBySocialIdDto}> = (props) => {
          const {data} = props ?? {};

          return  authControllerLoginBySocialId(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AuthControllerLoginBySocialIdMutationResult = NonNullable<Awaited<ReturnType<typeof authControllerLoginBySocialId>>>
    export type AuthControllerLoginBySocialIdMutationBody = LoginBySocialIdDto
    export type AuthControllerLoginBySocialIdMutationError = unknown

    export const useAuthControllerLoginBySocialId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerLoginBySocialId>>, TError,{data: LoginBySocialIdDto}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authControllerLoginBySocialId>>,
        TError,
        {data: LoginBySocialIdDto},
        TContext
      > => {

      const mutationOptions = getAuthControllerLoginBySocialIdMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    export const authControllerCheckPhoneNumberExists = (
    checkPhoneNumberExistsDto: CheckPhoneNumberExistsDto,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<boolean>(
      {url: `/auth/phone/exists`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: checkPhoneNumberExistsDto, signal
    },
      options);
    }
  


export const getAuthControllerCheckPhoneNumberExistsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerCheckPhoneNumberExists>>, TError,{data: CheckPhoneNumberExistsDto}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof authControllerCheckPhoneNumberExists>>, TError,{data: CheckPhoneNumberExistsDto}, TContext> => {

const mutationKey = ['authControllerCheckPhoneNumberExists'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerCheckPhoneNumberExists>>, {data: CheckPhoneNumberExistsDto}> = (props) => {
          const {data} = props ?? {};

          return  authControllerCheckPhoneNumberExists(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AuthControllerCheckPhoneNumberExistsMutationResult = NonNullable<Awaited<ReturnType<typeof authControllerCheckPhoneNumberExists>>>
    export type AuthControllerCheckPhoneNumberExistsMutationBody = CheckPhoneNumberExistsDto
    export type AuthControllerCheckPhoneNumberExistsMutationError = unknown

    export const useAuthControllerCheckPhoneNumberExists = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerCheckPhoneNumberExists>>, TError,{data: CheckPhoneNumberExistsDto}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authControllerCheckPhoneNumberExists>>,
        TError,
        {data: CheckPhoneNumberExistsDto},
        TContext
      > => {

      const mutationOptions = getAuthControllerCheckPhoneNumberExistsMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    export const authControllerSendVerificationCode = (
    sendVerificationCodeDto: SendVerificationCodeDto,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<string>(
      {url: `/auth/phone/send-verification`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: sendVerificationCodeDto, signal
    },
      options);
    }
  


export const getAuthControllerSendVerificationCodeMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerSendVerificationCode>>, TError,{data: SendVerificationCodeDto}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof authControllerSendVerificationCode>>, TError,{data: SendVerificationCodeDto}, TContext> => {

const mutationKey = ['authControllerSendVerificationCode'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerSendVerificationCode>>, {data: SendVerificationCodeDto}> = (props) => {
          const {data} = props ?? {};

          return  authControllerSendVerificationCode(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AuthControllerSendVerificationCodeMutationResult = NonNullable<Awaited<ReturnType<typeof authControllerSendVerificationCode>>>
    export type AuthControllerSendVerificationCodeMutationBody = SendVerificationCodeDto
    export type AuthControllerSendVerificationCodeMutationError = unknown

    export const useAuthControllerSendVerificationCode = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerSendVerificationCode>>, TError,{data: SendVerificationCodeDto}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authControllerSendVerificationCode>>,
        TError,
        {data: SendVerificationCodeDto},
        TContext
      > => {

      const mutationOptions = getAuthControllerSendVerificationCodeMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    export const authControllerVerifyPhoneNumber = (
    verifyPhoneNumberDto: VerifyPhoneNumberDto,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<boolean>(
      {url: `/auth/phone/verify`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: verifyPhoneNumberDto, signal
    },
      options);
    }
  


export const getAuthControllerVerifyPhoneNumberMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerVerifyPhoneNumber>>, TError,{data: VerifyPhoneNumberDto}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof authControllerVerifyPhoneNumber>>, TError,{data: VerifyPhoneNumberDto}, TContext> => {

const mutationKey = ['authControllerVerifyPhoneNumber'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerVerifyPhoneNumber>>, {data: VerifyPhoneNumberDto}> = (props) => {
          const {data} = props ?? {};

          return  authControllerVerifyPhoneNumber(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AuthControllerVerifyPhoneNumberMutationResult = NonNullable<Awaited<ReturnType<typeof authControllerVerifyPhoneNumber>>>
    export type AuthControllerVerifyPhoneNumberMutationBody = VerifyPhoneNumberDto
    export type AuthControllerVerifyPhoneNumberMutationError = unknown

    export const useAuthControllerVerifyPhoneNumber = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerVerifyPhoneNumber>>, TError,{data: VerifyPhoneNumberDto}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authControllerVerifyPhoneNumber>>,
        TError,
        {data: VerifyPhoneNumberDto},
        TContext
      > => {

      const mutationOptions = getAuthControllerVerifyPhoneNumberMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    