/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta API
 * Allta API 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  UploadImageRequest,
  UploadImageResponse
} from '.././models';

import { customInstance } from '../../libs/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const uploadControllerCreate = (
    uploadImageRequest: UploadImageRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      const formData = new FormData();
formData.append(`bucket`, uploadImageRequest.bucket)

      return customInstance<UploadImageResponse>(
      {url: `/upload/image`, method: 'POST',
      headers: {'Content-Type': 'multipart/form-data', },
       data: formData, signal
    },
      options);
    }
  


export const getUploadControllerCreateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadControllerCreate>>, TError,{data: UploadImageRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof uploadControllerCreate>>, TError,{data: UploadImageRequest}, TContext> => {

const mutationKey = ['uploadControllerCreate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof uploadControllerCreate>>, {data: UploadImageRequest}> = (props) => {
          const {data} = props ?? {};

          return  uploadControllerCreate(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UploadControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof uploadControllerCreate>>>
    export type UploadControllerCreateMutationBody = UploadImageRequest
    export type UploadControllerCreateMutationError = unknown

    export const useUploadControllerCreate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadControllerCreate>>, TError,{data: UploadImageRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof uploadControllerCreate>>,
        TError,
        {data: UploadImageRequest},
        TContext
      > => {

      const mutationOptions = getUploadControllerCreateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    