/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Allta API
 * Allta API 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetUserReferralCodeResponse,
  ReferralControllerVerifyReferralCodeParams,
  RegisterReferralCodeRequest,
  VerifyReferralCodeResponse
} from '.././models';

import { customInstance } from '../../libs/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const referralControllerGetUserReferralCode = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetUserReferralCodeResponse>(
      {url: `/referral`, method: 'GET', signal
    },
      options);
    }
  

export const getReferralControllerGetUserReferralCodeQueryKey = () => {
    return [`/referral`] as const;
    }

    
export const getReferralControllerGetUserReferralCodeQueryOptions = <TData = Awaited<ReturnType<typeof referralControllerGetUserReferralCode>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof referralControllerGetUserReferralCode>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getReferralControllerGetUserReferralCodeQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof referralControllerGetUserReferralCode>>> = ({ signal }) => referralControllerGetUserReferralCode(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof referralControllerGetUserReferralCode>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ReferralControllerGetUserReferralCodeQueryResult = NonNullable<Awaited<ReturnType<typeof referralControllerGetUserReferralCode>>>
export type ReferralControllerGetUserReferralCodeQueryError = unknown


export function useReferralControllerGetUserReferralCode<TData = Awaited<ReturnType<typeof referralControllerGetUserReferralCode>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof referralControllerGetUserReferralCode>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof referralControllerGetUserReferralCode>>,
          TError,
          Awaited<ReturnType<typeof referralControllerGetUserReferralCode>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReferralControllerGetUserReferralCode<TData = Awaited<ReturnType<typeof referralControllerGetUserReferralCode>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof referralControllerGetUserReferralCode>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof referralControllerGetUserReferralCode>>,
          TError,
          Awaited<ReturnType<typeof referralControllerGetUserReferralCode>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReferralControllerGetUserReferralCode<TData = Awaited<ReturnType<typeof referralControllerGetUserReferralCode>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof referralControllerGetUserReferralCode>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useReferralControllerGetUserReferralCode<TData = Awaited<ReturnType<typeof referralControllerGetUserReferralCode>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof referralControllerGetUserReferralCode>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getReferralControllerGetUserReferralCodeQueryOptions(options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const referralControllerVerifyReferralCode = (
    params: ReferralControllerVerifyReferralCodeParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<VerifyReferralCodeResponse>(
      {url: `/referral/verify`, method: 'GET',
        params, signal
    },
      options);
    }
  

export const getReferralControllerVerifyReferralCodeQueryKey = (params?: ReferralControllerVerifyReferralCodeParams,) => {
    return [`/referral/verify`, ...(params ? [params]: [])] as const;
    }

    
export const getReferralControllerVerifyReferralCodeQueryOptions = <TData = Awaited<ReturnType<typeof referralControllerVerifyReferralCode>>, TError = unknown>(params: ReferralControllerVerifyReferralCodeParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof referralControllerVerifyReferralCode>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getReferralControllerVerifyReferralCodeQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof referralControllerVerifyReferralCode>>> = ({ signal }) => referralControllerVerifyReferralCode(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof referralControllerVerifyReferralCode>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ReferralControllerVerifyReferralCodeQueryResult = NonNullable<Awaited<ReturnType<typeof referralControllerVerifyReferralCode>>>
export type ReferralControllerVerifyReferralCodeQueryError = unknown


export function useReferralControllerVerifyReferralCode<TData = Awaited<ReturnType<typeof referralControllerVerifyReferralCode>>, TError = unknown>(
 params: ReferralControllerVerifyReferralCodeParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof referralControllerVerifyReferralCode>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof referralControllerVerifyReferralCode>>,
          TError,
          Awaited<ReturnType<typeof referralControllerVerifyReferralCode>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReferralControllerVerifyReferralCode<TData = Awaited<ReturnType<typeof referralControllerVerifyReferralCode>>, TError = unknown>(
 params: ReferralControllerVerifyReferralCodeParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof referralControllerVerifyReferralCode>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof referralControllerVerifyReferralCode>>,
          TError,
          Awaited<ReturnType<typeof referralControllerVerifyReferralCode>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReferralControllerVerifyReferralCode<TData = Awaited<ReturnType<typeof referralControllerVerifyReferralCode>>, TError = unknown>(
 params: ReferralControllerVerifyReferralCodeParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof referralControllerVerifyReferralCode>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useReferralControllerVerifyReferralCode<TData = Awaited<ReturnType<typeof referralControllerVerifyReferralCode>>, TError = unknown>(
 params: ReferralControllerVerifyReferralCodeParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof referralControllerVerifyReferralCode>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getReferralControllerVerifyReferralCodeQueryOptions(params,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const referralControllerRegisterReferralCode = (
    registerReferralCodeRequest: RegisterReferralCodeRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetUserReferralCodeResponse>(
      {url: `/referral/register`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: registerReferralCodeRequest, signal
    },
      options);
    }
  


export const getReferralControllerRegisterReferralCodeMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof referralControllerRegisterReferralCode>>, TError,{data: RegisterReferralCodeRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof referralControllerRegisterReferralCode>>, TError,{data: RegisterReferralCodeRequest}, TContext> => {

const mutationKey = ['referralControllerRegisterReferralCode'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof referralControllerRegisterReferralCode>>, {data: RegisterReferralCodeRequest}> = (props) => {
          const {data} = props ?? {};

          return  referralControllerRegisterReferralCode(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ReferralControllerRegisterReferralCodeMutationResult = NonNullable<Awaited<ReturnType<typeof referralControllerRegisterReferralCode>>>
    export type ReferralControllerRegisterReferralCodeMutationBody = RegisterReferralCodeRequest
    export type ReferralControllerRegisterReferralCodeMutationError = unknown

    export const useReferralControllerRegisterReferralCode = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof referralControllerRegisterReferralCode>>, TError,{data: RegisterReferralCodeRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof referralControllerRegisterReferralCode>>,
        TError,
        {data: RegisterReferralCodeRequest},
        TContext
      > => {

      const mutationOptions = getReferralControllerRegisterReferralCodeMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    