/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Allta API
 * Allta의 REST API 문서입니다.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AddressControllerGetAddressesParams,
  GetAddressesResponse,
  RegisterAddressResponse,
  RegisterAddresssRequest
} from '.././models';

import { customInstance } from '../../libs/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const addressControllerGetAddresses = (
    params: AddressControllerGetAddressesParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetAddressesResponse>(
      {url: `/address`, method: 'GET',
        params, signal
    },
      options);
    }
  

export const getAddressControllerGetAddressesQueryKey = (params?: AddressControllerGetAddressesParams,) => {
    return [`/address`, ...(params ? [params]: [])] as const;
    }

    
export const getAddressControllerGetAddressesQueryOptions = <TData = Awaited<ReturnType<typeof addressControllerGetAddresses>>, TError = unknown>(params: AddressControllerGetAddressesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof addressControllerGetAddresses>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAddressControllerGetAddressesQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof addressControllerGetAddresses>>> = ({ signal }) => addressControllerGetAddresses(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof addressControllerGetAddresses>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AddressControllerGetAddressesQueryResult = NonNullable<Awaited<ReturnType<typeof addressControllerGetAddresses>>>
export type AddressControllerGetAddressesQueryError = unknown


export function useAddressControllerGetAddresses<TData = Awaited<ReturnType<typeof addressControllerGetAddresses>>, TError = unknown>(
 params: AddressControllerGetAddressesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof addressControllerGetAddresses>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof addressControllerGetAddresses>>,
          TError,
          Awaited<ReturnType<typeof addressControllerGetAddresses>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAddressControllerGetAddresses<TData = Awaited<ReturnType<typeof addressControllerGetAddresses>>, TError = unknown>(
 params: AddressControllerGetAddressesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof addressControllerGetAddresses>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof addressControllerGetAddresses>>,
          TError,
          Awaited<ReturnType<typeof addressControllerGetAddresses>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAddressControllerGetAddresses<TData = Awaited<ReturnType<typeof addressControllerGetAddresses>>, TError = unknown>(
 params: AddressControllerGetAddressesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof addressControllerGetAddresses>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useAddressControllerGetAddresses<TData = Awaited<ReturnType<typeof addressControllerGetAddresses>>, TError = unknown>(
 params: AddressControllerGetAddressesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof addressControllerGetAddresses>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAddressControllerGetAddressesQueryOptions(params,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const addressControllerRegisterAddresses = (
    registerAddresssRequest: RegisterAddresssRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<RegisterAddressResponse>(
      {url: `/address`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: registerAddresssRequest, signal
    },
      options);
    }
  


export const getAddressControllerRegisterAddressesMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addressControllerRegisterAddresses>>, TError,{data: RegisterAddresssRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof addressControllerRegisterAddresses>>, TError,{data: RegisterAddresssRequest}, TContext> => {

const mutationKey = ['addressControllerRegisterAddresses'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof addressControllerRegisterAddresses>>, {data: RegisterAddresssRequest}> = (props) => {
          const {data} = props ?? {};

          return  addressControllerRegisterAddresses(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AddressControllerRegisterAddressesMutationResult = NonNullable<Awaited<ReturnType<typeof addressControllerRegisterAddresses>>>
    export type AddressControllerRegisterAddressesMutationBody = RegisterAddresssRequest
    export type AddressControllerRegisterAddressesMutationError = unknown

    export const useAddressControllerRegisterAddresses = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addressControllerRegisterAddresses>>, TError,{data: RegisterAddresssRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof addressControllerRegisterAddresses>>,
        TError,
        {data: RegisterAddresssRequest},
        TContext
      > => {

      const mutationOptions = getAddressControllerRegisterAddressesMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    