/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Allta API
 * Allta의 REST API 문서입니다.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  SendManySmsDto
} from '.././models';

import { customInstance } from '../../libs/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const smsControllerSendManySms = (
    sendManySmsDto: SendManySmsDto,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/sms`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: sendManySmsDto, signal
    },
      options);
    }
  


export const getSmsControllerSendManySmsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof smsControllerSendManySms>>, TError,{data: SendManySmsDto}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof smsControllerSendManySms>>, TError,{data: SendManySmsDto}, TContext> => {

const mutationKey = ['smsControllerSendManySms'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof smsControllerSendManySms>>, {data: SendManySmsDto}> = (props) => {
          const {data} = props ?? {};

          return  smsControllerSendManySms(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type SmsControllerSendManySmsMutationResult = NonNullable<Awaited<ReturnType<typeof smsControllerSendManySms>>>
    export type SmsControllerSendManySmsMutationBody = SendManySmsDto
    export type SmsControllerSendManySmsMutationError = unknown

    export const useSmsControllerSendManySms = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof smsControllerSendManySms>>, TError,{data: SendManySmsDto}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof smsControllerSendManySms>>,
        TError,
        {data: SendManySmsDto},
        TContext
      > => {

      const mutationOptions = getSmsControllerSendManySmsMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    