/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Allta API
 * Allta API 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CheckPhoneNumberRequest,
  CheckPhoneNumberResponse,
  CreateUserRequest,
  CreateUserResponse,
  GetUserProfileResponse,
  RegisterExtraInfoRequest,
  RegisterExtraInfoResponse,
  SendVerificationCodeRequest,
  SendVerificationCodeResponse,
  UserControllerVerifyRefferalCodeParams,
  VerifyPhoneNumberRequest,
  VerifyPhoneNumberResponse,
  VerifyReferralCodeResponse
} from '.././models';

import { customInstance } from '../../libs/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const userControllerCheckPhoneNumber = (
    checkPhoneNumberRequest: CheckPhoneNumberRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<CheckPhoneNumberResponse>(
      {url: `/user/check/phone-number`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: checkPhoneNumberRequest, signal
    },
      options);
    }
  


export const getUserControllerCheckPhoneNumberMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof userControllerCheckPhoneNumber>>, TError,{data: CheckPhoneNumberRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof userControllerCheckPhoneNumber>>, TError,{data: CheckPhoneNumberRequest}, TContext> => {

const mutationKey = ['userControllerCheckPhoneNumber'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof userControllerCheckPhoneNumber>>, {data: CheckPhoneNumberRequest}> = (props) => {
          const {data} = props ?? {};

          return  userControllerCheckPhoneNumber(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UserControllerCheckPhoneNumberMutationResult = NonNullable<Awaited<ReturnType<typeof userControllerCheckPhoneNumber>>>
    export type UserControllerCheckPhoneNumberMutationBody = CheckPhoneNumberRequest
    export type UserControllerCheckPhoneNumberMutationError = unknown

    export const useUserControllerCheckPhoneNumber = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof userControllerCheckPhoneNumber>>, TError,{data: CheckPhoneNumberRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof userControllerCheckPhoneNumber>>,
        TError,
        {data: CheckPhoneNumberRequest},
        TContext
      > => {

      const mutationOptions = getUserControllerCheckPhoneNumberMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    export const userControllerSendVerificationCode = (
    sendVerificationCodeRequest: SendVerificationCodeRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<SendVerificationCodeResponse>(
      {url: `/user/send/verification-code`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: sendVerificationCodeRequest, signal
    },
      options);
    }
  


export const getUserControllerSendVerificationCodeMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof userControllerSendVerificationCode>>, TError,{data: SendVerificationCodeRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof userControllerSendVerificationCode>>, TError,{data: SendVerificationCodeRequest}, TContext> => {

const mutationKey = ['userControllerSendVerificationCode'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof userControllerSendVerificationCode>>, {data: SendVerificationCodeRequest}> = (props) => {
          const {data} = props ?? {};

          return  userControllerSendVerificationCode(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UserControllerSendVerificationCodeMutationResult = NonNullable<Awaited<ReturnType<typeof userControllerSendVerificationCode>>>
    export type UserControllerSendVerificationCodeMutationBody = SendVerificationCodeRequest
    export type UserControllerSendVerificationCodeMutationError = unknown

    export const useUserControllerSendVerificationCode = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof userControllerSendVerificationCode>>, TError,{data: SendVerificationCodeRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof userControllerSendVerificationCode>>,
        TError,
        {data: SendVerificationCodeRequest},
        TContext
      > => {

      const mutationOptions = getUserControllerSendVerificationCodeMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    export const userControllerVerifyPhoneNumber = (
    verifyPhoneNumberRequest: VerifyPhoneNumberRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<VerifyPhoneNumberResponse>(
      {url: `/user/verify/phone-number`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: verifyPhoneNumberRequest, signal
    },
      options);
    }
  


export const getUserControllerVerifyPhoneNumberMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof userControllerVerifyPhoneNumber>>, TError,{data: VerifyPhoneNumberRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof userControllerVerifyPhoneNumber>>, TError,{data: VerifyPhoneNumberRequest}, TContext> => {

const mutationKey = ['userControllerVerifyPhoneNumber'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof userControllerVerifyPhoneNumber>>, {data: VerifyPhoneNumberRequest}> = (props) => {
          const {data} = props ?? {};

          return  userControllerVerifyPhoneNumber(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UserControllerVerifyPhoneNumberMutationResult = NonNullable<Awaited<ReturnType<typeof userControllerVerifyPhoneNumber>>>
    export type UserControllerVerifyPhoneNumberMutationBody = VerifyPhoneNumberRequest
    export type UserControllerVerifyPhoneNumberMutationError = unknown

    export const useUserControllerVerifyPhoneNumber = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof userControllerVerifyPhoneNumber>>, TError,{data: VerifyPhoneNumberRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof userControllerVerifyPhoneNumber>>,
        TError,
        {data: VerifyPhoneNumberRequest},
        TContext
      > => {

      const mutationOptions = getUserControllerVerifyPhoneNumberMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    export const userControllerVerifyRefferalCode = (
    params: UserControllerVerifyRefferalCodeParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<VerifyReferralCodeResponse>(
      {url: `/user/verify/referral-code`, method: 'GET',
        params, signal
    },
      options);
    }
  

export const getUserControllerVerifyRefferalCodeQueryKey = (params?: UserControllerVerifyRefferalCodeParams,) => {
    return [`/user/verify/referral-code`, ...(params ? [params]: [])] as const;
    }

    
export const getUserControllerVerifyRefferalCodeQueryOptions = <TData = Awaited<ReturnType<typeof userControllerVerifyRefferalCode>>, TError = unknown>(params: UserControllerVerifyRefferalCodeParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof userControllerVerifyRefferalCode>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUserControllerVerifyRefferalCodeQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof userControllerVerifyRefferalCode>>> = ({ signal }) => userControllerVerifyRefferalCode(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof userControllerVerifyRefferalCode>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type UserControllerVerifyRefferalCodeQueryResult = NonNullable<Awaited<ReturnType<typeof userControllerVerifyRefferalCode>>>
export type UserControllerVerifyRefferalCodeQueryError = unknown


export function useUserControllerVerifyRefferalCode<TData = Awaited<ReturnType<typeof userControllerVerifyRefferalCode>>, TError = unknown>(
 params: UserControllerVerifyRefferalCodeParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof userControllerVerifyRefferalCode>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof userControllerVerifyRefferalCode>>,
          TError,
          Awaited<ReturnType<typeof userControllerVerifyRefferalCode>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUserControllerVerifyRefferalCode<TData = Awaited<ReturnType<typeof userControllerVerifyRefferalCode>>, TError = unknown>(
 params: UserControllerVerifyRefferalCodeParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof userControllerVerifyRefferalCode>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof userControllerVerifyRefferalCode>>,
          TError,
          Awaited<ReturnType<typeof userControllerVerifyRefferalCode>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUserControllerVerifyRefferalCode<TData = Awaited<ReturnType<typeof userControllerVerifyRefferalCode>>, TError = unknown>(
 params: UserControllerVerifyRefferalCodeParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof userControllerVerifyRefferalCode>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useUserControllerVerifyRefferalCode<TData = Awaited<ReturnType<typeof userControllerVerifyRefferalCode>>, TError = unknown>(
 params: UserControllerVerifyRefferalCodeParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof userControllerVerifyRefferalCode>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getUserControllerVerifyRefferalCodeQueryOptions(params,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const userControllerCreateUser = (
    createUserRequest: CreateUserRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<CreateUserResponse>(
      {url: `/user/create`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createUserRequest, signal
    },
      options);
    }
  


export const getUserControllerCreateUserMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof userControllerCreateUser>>, TError,{data: CreateUserRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof userControllerCreateUser>>, TError,{data: CreateUserRequest}, TContext> => {

const mutationKey = ['userControllerCreateUser'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof userControllerCreateUser>>, {data: CreateUserRequest}> = (props) => {
          const {data} = props ?? {};

          return  userControllerCreateUser(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UserControllerCreateUserMutationResult = NonNullable<Awaited<ReturnType<typeof userControllerCreateUser>>>
    export type UserControllerCreateUserMutationBody = CreateUserRequest
    export type UserControllerCreateUserMutationError = unknown

    export const useUserControllerCreateUser = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof userControllerCreateUser>>, TError,{data: CreateUserRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof userControllerCreateUser>>,
        TError,
        {data: CreateUserRequest},
        TContext
      > => {

      const mutationOptions = getUserControllerCreateUserMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    export const userControllerRegisterExtraInfo = (
    registerExtraInfoRequest: RegisterExtraInfoRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<RegisterExtraInfoResponse>(
      {url: `/user/register/extar-info`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: registerExtraInfoRequest, signal
    },
      options);
    }
  


export const getUserControllerRegisterExtraInfoMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof userControllerRegisterExtraInfo>>, TError,{data: RegisterExtraInfoRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof userControllerRegisterExtraInfo>>, TError,{data: RegisterExtraInfoRequest}, TContext> => {

const mutationKey = ['userControllerRegisterExtraInfo'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof userControllerRegisterExtraInfo>>, {data: RegisterExtraInfoRequest}> = (props) => {
          const {data} = props ?? {};

          return  userControllerRegisterExtraInfo(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UserControllerRegisterExtraInfoMutationResult = NonNullable<Awaited<ReturnType<typeof userControllerRegisterExtraInfo>>>
    export type UserControllerRegisterExtraInfoMutationBody = RegisterExtraInfoRequest
    export type UserControllerRegisterExtraInfoMutationError = unknown

    export const useUserControllerRegisterExtraInfo = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof userControllerRegisterExtraInfo>>, TError,{data: RegisterExtraInfoRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof userControllerRegisterExtraInfo>>,
        TError,
        {data: RegisterExtraInfoRequest},
        TContext
      > => {

      const mutationOptions = getUserControllerRegisterExtraInfoMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    export const userControllerGetUserProfile = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetUserProfileResponse>(
      {url: `/user/user/profile`, method: 'GET', signal
    },
      options);
    }
  

export const getUserControllerGetUserProfileQueryKey = () => {
    return [`/user/user/profile`] as const;
    }

    
export const getUserControllerGetUserProfileQueryOptions = <TData = Awaited<ReturnType<typeof userControllerGetUserProfile>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof userControllerGetUserProfile>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUserControllerGetUserProfileQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof userControllerGetUserProfile>>> = ({ signal }) => userControllerGetUserProfile(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof userControllerGetUserProfile>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type UserControllerGetUserProfileQueryResult = NonNullable<Awaited<ReturnType<typeof userControllerGetUserProfile>>>
export type UserControllerGetUserProfileQueryError = unknown


export function useUserControllerGetUserProfile<TData = Awaited<ReturnType<typeof userControllerGetUserProfile>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof userControllerGetUserProfile>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof userControllerGetUserProfile>>,
          TError,
          Awaited<ReturnType<typeof userControllerGetUserProfile>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUserControllerGetUserProfile<TData = Awaited<ReturnType<typeof userControllerGetUserProfile>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof userControllerGetUserProfile>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof userControllerGetUserProfile>>,
          TError,
          Awaited<ReturnType<typeof userControllerGetUserProfile>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUserControllerGetUserProfile<TData = Awaited<ReturnType<typeof userControllerGetUserProfile>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof userControllerGetUserProfile>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useUserControllerGetUserProfile<TData = Awaited<ReturnType<typeof userControllerGetUserProfile>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof userControllerGetUserProfile>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getUserControllerGetUserProfileQueryOptions(options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



