/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta API
 * Allta API 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CheckIsRejoinResponse,
  CheckPhoneNumberRequest,
  CheckPhoneNumberResponse,
  CreateUserRequest,
  CreateUserResponse,
  GetMarketingAgreementStatusResponse,
  GetUserProfileResponse,
  RegisterExtraInfoRequest,
  RegisterExtraInfoResponse,
  SendVerificationCodeRequest,
  SendVerificationCodeResponse,
  UpdateMarketingAgreementStatusRequest,
  UpdateMarketingAgreementStatusResponse,
  UpdateUserProfileRequest,
  UpdateUserProfileResponse,
  UserControllerCheckIsRejoinParams,
  VerifyPhoneNumberRequest,
  VerifyPhoneNumberResponse,
  WithdrawalUserRequest,
  WithdrawalUserResponse
} from '.././models';

import { customInstance } from '../../libs/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const userControllerCheckPhoneNumber = (
    checkPhoneNumberRequest: CheckPhoneNumberRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<CheckPhoneNumberResponse>(
      {url: `/user/check/phone-number`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: checkPhoneNumberRequest, signal
    },
      options);
    }
  


export const getUserControllerCheckPhoneNumberMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof userControllerCheckPhoneNumber>>, TError,{data: CheckPhoneNumberRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof userControllerCheckPhoneNumber>>, TError,{data: CheckPhoneNumberRequest}, TContext> => {

const mutationKey = ['userControllerCheckPhoneNumber'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof userControllerCheckPhoneNumber>>, {data: CheckPhoneNumberRequest}> = (props) => {
          const {data} = props ?? {};

          return  userControllerCheckPhoneNumber(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UserControllerCheckPhoneNumberMutationResult = NonNullable<Awaited<ReturnType<typeof userControllerCheckPhoneNumber>>>
    export type UserControllerCheckPhoneNumberMutationBody = CheckPhoneNumberRequest
    export type UserControllerCheckPhoneNumberMutationError = unknown

    export const useUserControllerCheckPhoneNumber = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof userControllerCheckPhoneNumber>>, TError,{data: CheckPhoneNumberRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof userControllerCheckPhoneNumber>>,
        TError,
        {data: CheckPhoneNumberRequest},
        TContext
      > => {

      const mutationOptions = getUserControllerCheckPhoneNumberMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const userControllerSendVerificationCode = (
    sendVerificationCodeRequest: SendVerificationCodeRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<SendVerificationCodeResponse>(
      {url: `/user/send/verification-code`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: sendVerificationCodeRequest, signal
    },
      options);
    }
  


export const getUserControllerSendVerificationCodeMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof userControllerSendVerificationCode>>, TError,{data: SendVerificationCodeRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof userControllerSendVerificationCode>>, TError,{data: SendVerificationCodeRequest}, TContext> => {

const mutationKey = ['userControllerSendVerificationCode'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof userControllerSendVerificationCode>>, {data: SendVerificationCodeRequest}> = (props) => {
          const {data} = props ?? {};

          return  userControllerSendVerificationCode(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UserControllerSendVerificationCodeMutationResult = NonNullable<Awaited<ReturnType<typeof userControllerSendVerificationCode>>>
    export type UserControllerSendVerificationCodeMutationBody = SendVerificationCodeRequest
    export type UserControllerSendVerificationCodeMutationError = unknown

    export const useUserControllerSendVerificationCode = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof userControllerSendVerificationCode>>, TError,{data: SendVerificationCodeRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof userControllerSendVerificationCode>>,
        TError,
        {data: SendVerificationCodeRequest},
        TContext
      > => {

      const mutationOptions = getUserControllerSendVerificationCodeMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const userControllerVerifyPhoneNumber = (
    verifyPhoneNumberRequest: VerifyPhoneNumberRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<VerifyPhoneNumberResponse>(
      {url: `/user/verify/phone-number`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: verifyPhoneNumberRequest, signal
    },
      options);
    }
  


export const getUserControllerVerifyPhoneNumberMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof userControllerVerifyPhoneNumber>>, TError,{data: VerifyPhoneNumberRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof userControllerVerifyPhoneNumber>>, TError,{data: VerifyPhoneNumberRequest}, TContext> => {

const mutationKey = ['userControllerVerifyPhoneNumber'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof userControllerVerifyPhoneNumber>>, {data: VerifyPhoneNumberRequest}> = (props) => {
          const {data} = props ?? {};

          return  userControllerVerifyPhoneNumber(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UserControllerVerifyPhoneNumberMutationResult = NonNullable<Awaited<ReturnType<typeof userControllerVerifyPhoneNumber>>>
    export type UserControllerVerifyPhoneNumberMutationBody = VerifyPhoneNumberRequest
    export type UserControllerVerifyPhoneNumberMutationError = unknown

    export const useUserControllerVerifyPhoneNumber = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof userControllerVerifyPhoneNumber>>, TError,{data: VerifyPhoneNumberRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof userControllerVerifyPhoneNumber>>,
        TError,
        {data: VerifyPhoneNumberRequest},
        TContext
      > => {

      const mutationOptions = getUserControllerVerifyPhoneNumberMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const userControllerCheckIsRejoin = (
    params: UserControllerCheckIsRejoinParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<CheckIsRejoinResponse>(
      {url: `/user/rejoin`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getUserControllerCheckIsRejoinQueryKey = (params?: UserControllerCheckIsRejoinParams,) => {
    return [
    `/user/rejoin`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getUserControllerCheckIsRejoinQueryOptions = <TData = Awaited<ReturnType<typeof userControllerCheckIsRejoin>>, TError = unknown>(params: UserControllerCheckIsRejoinParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof userControllerCheckIsRejoin>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUserControllerCheckIsRejoinQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof userControllerCheckIsRejoin>>> = ({ signal }) => userControllerCheckIsRejoin(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof userControllerCheckIsRejoin>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type UserControllerCheckIsRejoinQueryResult = NonNullable<Awaited<ReturnType<typeof userControllerCheckIsRejoin>>>
export type UserControllerCheckIsRejoinQueryError = unknown


export function useUserControllerCheckIsRejoin<TData = Awaited<ReturnType<typeof userControllerCheckIsRejoin>>, TError = unknown>(
 params: UserControllerCheckIsRejoinParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof userControllerCheckIsRejoin>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof userControllerCheckIsRejoin>>,
          TError,
          Awaited<ReturnType<typeof userControllerCheckIsRejoin>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUserControllerCheckIsRejoin<TData = Awaited<ReturnType<typeof userControllerCheckIsRejoin>>, TError = unknown>(
 params: UserControllerCheckIsRejoinParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof userControllerCheckIsRejoin>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof userControllerCheckIsRejoin>>,
          TError,
          Awaited<ReturnType<typeof userControllerCheckIsRejoin>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUserControllerCheckIsRejoin<TData = Awaited<ReturnType<typeof userControllerCheckIsRejoin>>, TError = unknown>(
 params: UserControllerCheckIsRejoinParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof userControllerCheckIsRejoin>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useUserControllerCheckIsRejoin<TData = Awaited<ReturnType<typeof userControllerCheckIsRejoin>>, TError = unknown>(
 params: UserControllerCheckIsRejoinParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof userControllerCheckIsRejoin>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getUserControllerCheckIsRejoinQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const userControllerCreateUser = (
    createUserRequest: CreateUserRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<CreateUserResponse>(
      {url: `/user/create`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createUserRequest, signal
    },
      options);
    }
  


export const getUserControllerCreateUserMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof userControllerCreateUser>>, TError,{data: CreateUserRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof userControllerCreateUser>>, TError,{data: CreateUserRequest}, TContext> => {

const mutationKey = ['userControllerCreateUser'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof userControllerCreateUser>>, {data: CreateUserRequest}> = (props) => {
          const {data} = props ?? {};

          return  userControllerCreateUser(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UserControllerCreateUserMutationResult = NonNullable<Awaited<ReturnType<typeof userControllerCreateUser>>>
    export type UserControllerCreateUserMutationBody = CreateUserRequest
    export type UserControllerCreateUserMutationError = unknown

    export const useUserControllerCreateUser = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof userControllerCreateUser>>, TError,{data: CreateUserRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof userControllerCreateUser>>,
        TError,
        {data: CreateUserRequest},
        TContext
      > => {

      const mutationOptions = getUserControllerCreateUserMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const userControllerRegisterExtraInfo = (
    registerExtraInfoRequest: RegisterExtraInfoRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<RegisterExtraInfoResponse>(
      {url: `/user/register/extar-info`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: registerExtraInfoRequest, signal
    },
      options);
    }
  


export const getUserControllerRegisterExtraInfoMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof userControllerRegisterExtraInfo>>, TError,{data: RegisterExtraInfoRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof userControllerRegisterExtraInfo>>, TError,{data: RegisterExtraInfoRequest}, TContext> => {

const mutationKey = ['userControllerRegisterExtraInfo'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof userControllerRegisterExtraInfo>>, {data: RegisterExtraInfoRequest}> = (props) => {
          const {data} = props ?? {};

          return  userControllerRegisterExtraInfo(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UserControllerRegisterExtraInfoMutationResult = NonNullable<Awaited<ReturnType<typeof userControllerRegisterExtraInfo>>>
    export type UserControllerRegisterExtraInfoMutationBody = RegisterExtraInfoRequest
    export type UserControllerRegisterExtraInfoMutationError = unknown

    export const useUserControllerRegisterExtraInfo = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof userControllerRegisterExtraInfo>>, TError,{data: RegisterExtraInfoRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof userControllerRegisterExtraInfo>>,
        TError,
        {data: RegisterExtraInfoRequest},
        TContext
      > => {

      const mutationOptions = getUserControllerRegisterExtraInfoMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const userControllerGetUserProfile = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetUserProfileResponse>(
      {url: `/user/profile`, method: 'GET', signal
    },
      options);
    }
  



export const getUserControllerGetUserProfileQueryKey = () => {
    return [
    `/user/profile`
    ] as const;
    }

    
export const getUserControllerGetUserProfileQueryOptions = <TData = Awaited<ReturnType<typeof userControllerGetUserProfile>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof userControllerGetUserProfile>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUserControllerGetUserProfileQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof userControllerGetUserProfile>>> = ({ signal }) => userControllerGetUserProfile(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof userControllerGetUserProfile>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type UserControllerGetUserProfileQueryResult = NonNullable<Awaited<ReturnType<typeof userControllerGetUserProfile>>>
export type UserControllerGetUserProfileQueryError = unknown


export function useUserControllerGetUserProfile<TData = Awaited<ReturnType<typeof userControllerGetUserProfile>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof userControllerGetUserProfile>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof userControllerGetUserProfile>>,
          TError,
          Awaited<ReturnType<typeof userControllerGetUserProfile>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUserControllerGetUserProfile<TData = Awaited<ReturnType<typeof userControllerGetUserProfile>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof userControllerGetUserProfile>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof userControllerGetUserProfile>>,
          TError,
          Awaited<ReturnType<typeof userControllerGetUserProfile>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUserControllerGetUserProfile<TData = Awaited<ReturnType<typeof userControllerGetUserProfile>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof userControllerGetUserProfile>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useUserControllerGetUserProfile<TData = Awaited<ReturnType<typeof userControllerGetUserProfile>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof userControllerGetUserProfile>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getUserControllerGetUserProfileQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const userControllerUpdateUserProfile = (
    updateUserProfileRequest: UpdateUserProfileRequest,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<UpdateUserProfileResponse>(
      {url: `/user/profile`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateUserProfileRequest
    },
      options);
    }
  


export const getUserControllerUpdateUserProfileMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof userControllerUpdateUserProfile>>, TError,{data: UpdateUserProfileRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof userControllerUpdateUserProfile>>, TError,{data: UpdateUserProfileRequest}, TContext> => {

const mutationKey = ['userControllerUpdateUserProfile'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof userControllerUpdateUserProfile>>, {data: UpdateUserProfileRequest}> = (props) => {
          const {data} = props ?? {};

          return  userControllerUpdateUserProfile(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UserControllerUpdateUserProfileMutationResult = NonNullable<Awaited<ReturnType<typeof userControllerUpdateUserProfile>>>
    export type UserControllerUpdateUserProfileMutationBody = UpdateUserProfileRequest
    export type UserControllerUpdateUserProfileMutationError = unknown

    export const useUserControllerUpdateUserProfile = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof userControllerUpdateUserProfile>>, TError,{data: UpdateUserProfileRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof userControllerUpdateUserProfile>>,
        TError,
        {data: UpdateUserProfileRequest},
        TContext
      > => {

      const mutationOptions = getUserControllerUpdateUserProfileMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const userControllerGetMarketingAgreementStatus = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetMarketingAgreementStatusResponse>(
      {url: `/user/marketing-status`, method: 'GET', signal
    },
      options);
    }
  



export const getUserControllerGetMarketingAgreementStatusQueryKey = () => {
    return [
    `/user/marketing-status`
    ] as const;
    }

    
export const getUserControllerGetMarketingAgreementStatusQueryOptions = <TData = Awaited<ReturnType<typeof userControllerGetMarketingAgreementStatus>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof userControllerGetMarketingAgreementStatus>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUserControllerGetMarketingAgreementStatusQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof userControllerGetMarketingAgreementStatus>>> = ({ signal }) => userControllerGetMarketingAgreementStatus(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof userControllerGetMarketingAgreementStatus>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type UserControllerGetMarketingAgreementStatusQueryResult = NonNullable<Awaited<ReturnType<typeof userControllerGetMarketingAgreementStatus>>>
export type UserControllerGetMarketingAgreementStatusQueryError = unknown


export function useUserControllerGetMarketingAgreementStatus<TData = Awaited<ReturnType<typeof userControllerGetMarketingAgreementStatus>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof userControllerGetMarketingAgreementStatus>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof userControllerGetMarketingAgreementStatus>>,
          TError,
          Awaited<ReturnType<typeof userControllerGetMarketingAgreementStatus>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUserControllerGetMarketingAgreementStatus<TData = Awaited<ReturnType<typeof userControllerGetMarketingAgreementStatus>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof userControllerGetMarketingAgreementStatus>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof userControllerGetMarketingAgreementStatus>>,
          TError,
          Awaited<ReturnType<typeof userControllerGetMarketingAgreementStatus>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUserControllerGetMarketingAgreementStatus<TData = Awaited<ReturnType<typeof userControllerGetMarketingAgreementStatus>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof userControllerGetMarketingAgreementStatus>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useUserControllerGetMarketingAgreementStatus<TData = Awaited<ReturnType<typeof userControllerGetMarketingAgreementStatus>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof userControllerGetMarketingAgreementStatus>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getUserControllerGetMarketingAgreementStatusQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const userControllerUpdateMarketingAgreementStatus = (
    updateMarketingAgreementStatusRequest: UpdateMarketingAgreementStatusRequest,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<UpdateMarketingAgreementStatusResponse>(
      {url: `/user/marketing-status`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateMarketingAgreementStatusRequest
    },
      options);
    }
  


export const getUserControllerUpdateMarketingAgreementStatusMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof userControllerUpdateMarketingAgreementStatus>>, TError,{data: UpdateMarketingAgreementStatusRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof userControllerUpdateMarketingAgreementStatus>>, TError,{data: UpdateMarketingAgreementStatusRequest}, TContext> => {

const mutationKey = ['userControllerUpdateMarketingAgreementStatus'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof userControllerUpdateMarketingAgreementStatus>>, {data: UpdateMarketingAgreementStatusRequest}> = (props) => {
          const {data} = props ?? {};

          return  userControllerUpdateMarketingAgreementStatus(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UserControllerUpdateMarketingAgreementStatusMutationResult = NonNullable<Awaited<ReturnType<typeof userControllerUpdateMarketingAgreementStatus>>>
    export type UserControllerUpdateMarketingAgreementStatusMutationBody = UpdateMarketingAgreementStatusRequest
    export type UserControllerUpdateMarketingAgreementStatusMutationError = unknown

    export const useUserControllerUpdateMarketingAgreementStatus = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof userControllerUpdateMarketingAgreementStatus>>, TError,{data: UpdateMarketingAgreementStatusRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof userControllerUpdateMarketingAgreementStatus>>,
        TError,
        {data: UpdateMarketingAgreementStatusRequest},
        TContext
      > => {

      const mutationOptions = getUserControllerUpdateMarketingAgreementStatusMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const userControllerWithdrawalUser = (
    withdrawalUserRequest: WithdrawalUserRequest,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<WithdrawalUserResponse>(
      {url: `/user/withdrawal`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: withdrawalUserRequest
    },
      options);
    }
  


export const getUserControllerWithdrawalUserMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof userControllerWithdrawalUser>>, TError,{data: WithdrawalUserRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof userControllerWithdrawalUser>>, TError,{data: WithdrawalUserRequest}, TContext> => {

const mutationKey = ['userControllerWithdrawalUser'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof userControllerWithdrawalUser>>, {data: WithdrawalUserRequest}> = (props) => {
          const {data} = props ?? {};

          return  userControllerWithdrawalUser(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UserControllerWithdrawalUserMutationResult = NonNullable<Awaited<ReturnType<typeof userControllerWithdrawalUser>>>
    export type UserControllerWithdrawalUserMutationBody = WithdrawalUserRequest
    export type UserControllerWithdrawalUserMutationError = unknown

    export const useUserControllerWithdrawalUser = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof userControllerWithdrawalUser>>, TError,{data: WithdrawalUserRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof userControllerWithdrawalUser>>,
        TError,
        {data: WithdrawalUserRequest},
        TContext
      > => {

      const mutationOptions = getUserControllerWithdrawalUserMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    