/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Allta API
 * Allta의 REST API 문서입니다.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  CheckUserBySocialIdDto,
  SendVerificationCodeDto,
  VerifyPhoneNumberDto
} from '.././models';





export const authControllerCheckUserBySocialId = (
    checkUserBySocialIdDto: CheckUserBySocialIdDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.get(
      `/auth/social/check`,options
    );
  }


export const getAuthControllerCheckUserBySocialIdQueryKey = (checkUserBySocialIdDto: CheckUserBySocialIdDto,) => {
    return [`/auth/social/check`, checkUserBySocialIdDto] as const;
    }

    
export const getAuthControllerCheckUserBySocialIdQueryOptions = <TData = Awaited<ReturnType<typeof authControllerCheckUserBySocialId>>, TError = AxiosError<unknown>>(checkUserBySocialIdDto: CheckUserBySocialIdDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerCheckUserBySocialId>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAuthControllerCheckUserBySocialIdQueryKey(checkUserBySocialIdDto);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof authControllerCheckUserBySocialId>>> = ({ signal }) => authControllerCheckUserBySocialId(checkUserBySocialIdDto, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof authControllerCheckUserBySocialId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AuthControllerCheckUserBySocialIdQueryResult = NonNullable<Awaited<ReturnType<typeof authControllerCheckUserBySocialId>>>
export type AuthControllerCheckUserBySocialIdQueryError = AxiosError<unknown>


export function useAuthControllerCheckUserBySocialId<TData = Awaited<ReturnType<typeof authControllerCheckUserBySocialId>>, TError = AxiosError<unknown>>(
 checkUserBySocialIdDto: CheckUserBySocialIdDto, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerCheckUserBySocialId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof authControllerCheckUserBySocialId>>,
          TError,
          Awaited<ReturnType<typeof authControllerCheckUserBySocialId>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuthControllerCheckUserBySocialId<TData = Awaited<ReturnType<typeof authControllerCheckUserBySocialId>>, TError = AxiosError<unknown>>(
 checkUserBySocialIdDto: CheckUserBySocialIdDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerCheckUserBySocialId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof authControllerCheckUserBySocialId>>,
          TError,
          Awaited<ReturnType<typeof authControllerCheckUserBySocialId>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuthControllerCheckUserBySocialId<TData = Awaited<ReturnType<typeof authControllerCheckUserBySocialId>>, TError = AxiosError<unknown>>(
 checkUserBySocialIdDto: CheckUserBySocialIdDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerCheckUserBySocialId>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useAuthControllerCheckUserBySocialId<TData = Awaited<ReturnType<typeof authControllerCheckUserBySocialId>>, TError = AxiosError<unknown>>(
 checkUserBySocialIdDto: CheckUserBySocialIdDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerCheckUserBySocialId>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAuthControllerCheckUserBySocialIdQueryOptions(checkUserBySocialIdDto,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const authControllerKakaoCallback = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.get(
      `/auth/kakao/login`,options
    );
  }


export const getAuthControllerKakaoCallbackQueryKey = () => {
    return [`/auth/kakao/login`] as const;
    }

    
export const getAuthControllerKakaoCallbackQueryOptions = <TData = Awaited<ReturnType<typeof authControllerKakaoCallback>>, TError = AxiosError<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerKakaoCallback>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAuthControllerKakaoCallbackQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof authControllerKakaoCallback>>> = ({ signal }) => authControllerKakaoCallback({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof authControllerKakaoCallback>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AuthControllerKakaoCallbackQueryResult = NonNullable<Awaited<ReturnType<typeof authControllerKakaoCallback>>>
export type AuthControllerKakaoCallbackQueryError = AxiosError<unknown>


export function useAuthControllerKakaoCallback<TData = Awaited<ReturnType<typeof authControllerKakaoCallback>>, TError = AxiosError<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerKakaoCallback>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof authControllerKakaoCallback>>,
          TError,
          Awaited<ReturnType<typeof authControllerKakaoCallback>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuthControllerKakaoCallback<TData = Awaited<ReturnType<typeof authControllerKakaoCallback>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerKakaoCallback>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof authControllerKakaoCallback>>,
          TError,
          Awaited<ReturnType<typeof authControllerKakaoCallback>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuthControllerKakaoCallback<TData = Awaited<ReturnType<typeof authControllerKakaoCallback>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerKakaoCallback>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useAuthControllerKakaoCallback<TData = Awaited<ReturnType<typeof authControllerKakaoCallback>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerKakaoCallback>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAuthControllerKakaoCallbackQueryOptions(options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const authControllerSendVerificationCode = (
    sendVerificationCodeDto: SendVerificationCodeDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.post(
      `/auth/phone/send-verification`,
      sendVerificationCodeDto,options
    );
  }



export const getAuthControllerSendVerificationCodeMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerSendVerificationCode>>, TError,{data: SendVerificationCodeDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof authControllerSendVerificationCode>>, TError,{data: SendVerificationCodeDto}, TContext> => {

const mutationKey = ['authControllerSendVerificationCode'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerSendVerificationCode>>, {data: SendVerificationCodeDto}> = (props) => {
          const {data} = props ?? {};

          return  authControllerSendVerificationCode(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AuthControllerSendVerificationCodeMutationResult = NonNullable<Awaited<ReturnType<typeof authControllerSendVerificationCode>>>
    export type AuthControllerSendVerificationCodeMutationBody = SendVerificationCodeDto
    export type AuthControllerSendVerificationCodeMutationError = AxiosError<unknown>

    export const useAuthControllerSendVerificationCode = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerSendVerificationCode>>, TError,{data: SendVerificationCodeDto}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authControllerSendVerificationCode>>,
        TError,
        {data: SendVerificationCodeDto},
        TContext
      > => {

      const mutationOptions = getAuthControllerSendVerificationCodeMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    export const authControllerVerifyPhoneNumber = (
    verifyPhoneNumberDto: VerifyPhoneNumberDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.post(
      `/auth/phone/verify`,
      verifyPhoneNumberDto,options
    );
  }



export const getAuthControllerVerifyPhoneNumberMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerVerifyPhoneNumber>>, TError,{data: VerifyPhoneNumberDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof authControllerVerifyPhoneNumber>>, TError,{data: VerifyPhoneNumberDto}, TContext> => {

const mutationKey = ['authControllerVerifyPhoneNumber'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerVerifyPhoneNumber>>, {data: VerifyPhoneNumberDto}> = (props) => {
          const {data} = props ?? {};

          return  authControllerVerifyPhoneNumber(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AuthControllerVerifyPhoneNumberMutationResult = NonNullable<Awaited<ReturnType<typeof authControllerVerifyPhoneNumber>>>
    export type AuthControllerVerifyPhoneNumberMutationBody = VerifyPhoneNumberDto
    export type AuthControllerVerifyPhoneNumberMutationError = AxiosError<unknown>

    export const useAuthControllerVerifyPhoneNumber = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerVerifyPhoneNumber>>, TError,{data: VerifyPhoneNumberDto}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authControllerVerifyPhoneNumber>>,
        TError,
        {data: VerifyPhoneNumberDto},
        TContext
      > => {

      const mutationOptions = getAuthControllerVerifyPhoneNumberMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    