/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta API
 * Allta API 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  VerifyReceiptRequest,
  VerifyReceiptResponse
} from '.././models';

import { customInstance } from '../../libs/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const receiptControllerVerifyReceipt = (
    verifyReceiptRequest: VerifyReceiptRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<VerifyReceiptResponse>(
      {url: `/receipt/verify`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: verifyReceiptRequest, signal
    },
      options);
    }
  


export const getReceiptControllerVerifyReceiptMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof receiptControllerVerifyReceipt>>, TError,{data: VerifyReceiptRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof receiptControllerVerifyReceipt>>, TError,{data: VerifyReceiptRequest}, TContext> => {

const mutationKey = ['receiptControllerVerifyReceipt'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof receiptControllerVerifyReceipt>>, {data: VerifyReceiptRequest}> = (props) => {
          const {data} = props ?? {};

          return  receiptControllerVerifyReceipt(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ReceiptControllerVerifyReceiptMutationResult = NonNullable<Awaited<ReturnType<typeof receiptControllerVerifyReceipt>>>
    export type ReceiptControllerVerifyReceiptMutationBody = VerifyReceiptRequest
    export type ReceiptControllerVerifyReceiptMutationError = unknown

    export const useReceiptControllerVerifyReceipt = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof receiptControllerVerifyReceipt>>, TError,{data: VerifyReceiptRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof receiptControllerVerifyReceipt>>,
        TError,
        {data: VerifyReceiptRequest},
        TContext
      > => {

      const mutationOptions = getReceiptControllerVerifyReceiptMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    