/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Allta API
 * Allta의 REST API 문서입니다.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  CreateCardDto
} from '.././models';

import { customInstance } from '../../libs/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const cardControllerCreate = (
    createCardDto: CreateCardDto,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<null>(
      {url: `/card`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createCardDto, signal
    },
      options);
    }
  


export const getCardControllerCreateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof cardControllerCreate>>, TError,{data: CreateCardDto}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof cardControllerCreate>>, TError,{data: CreateCardDto}, TContext> => {

const mutationKey = ['cardControllerCreate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof cardControllerCreate>>, {data: CreateCardDto}> = (props) => {
          const {data} = props ?? {};

          return  cardControllerCreate(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CardControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof cardControllerCreate>>>
    export type CardControllerCreateMutationBody = CreateCardDto
    export type CardControllerCreateMutationError = unknown

    export const useCardControllerCreate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof cardControllerCreate>>, TError,{data: CreateCardDto}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof cardControllerCreate>>,
        TError,
        {data: CreateCardDto},
        TContext
      > => {

      const mutationOptions = getCardControllerCreateMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    