/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Allta API
 * Allta API 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetCardListResponse,
  RegisterCardRequest,
  RegisterCardResponse
} from '.././models';

import { customInstance } from '../../libs/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const cardControllerGetCardList = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetCardListResponse>(
      {url: `/card`, method: 'GET', signal
    },
      options);
    }
  

export const getCardControllerGetCardListQueryKey = () => {
    return [`/card`] as const;
    }

    
export const getCardControllerGetCardListQueryOptions = <TData = Awaited<ReturnType<typeof cardControllerGetCardList>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof cardControllerGetCardList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCardControllerGetCardListQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof cardControllerGetCardList>>> = ({ signal }) => cardControllerGetCardList(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof cardControllerGetCardList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CardControllerGetCardListQueryResult = NonNullable<Awaited<ReturnType<typeof cardControllerGetCardList>>>
export type CardControllerGetCardListQueryError = unknown


export function useCardControllerGetCardList<TData = Awaited<ReturnType<typeof cardControllerGetCardList>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof cardControllerGetCardList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof cardControllerGetCardList>>,
          TError,
          Awaited<ReturnType<typeof cardControllerGetCardList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCardControllerGetCardList<TData = Awaited<ReturnType<typeof cardControllerGetCardList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof cardControllerGetCardList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof cardControllerGetCardList>>,
          TError,
          Awaited<ReturnType<typeof cardControllerGetCardList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCardControllerGetCardList<TData = Awaited<ReturnType<typeof cardControllerGetCardList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof cardControllerGetCardList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useCardControllerGetCardList<TData = Awaited<ReturnType<typeof cardControllerGetCardList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof cardControllerGetCardList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCardControllerGetCardListQueryOptions(options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const cardControllerRegisterCard = (
    registerCardRequest: RegisterCardRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<RegisterCardResponse>(
      {url: `/card`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: registerCardRequest, signal
    },
      options);
    }
  


export const getCardControllerRegisterCardMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof cardControllerRegisterCard>>, TError,{data: RegisterCardRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof cardControllerRegisterCard>>, TError,{data: RegisterCardRequest}, TContext> => {

const mutationKey = ['cardControllerRegisterCard'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof cardControllerRegisterCard>>, {data: RegisterCardRequest}> = (props) => {
          const {data} = props ?? {};

          return  cardControllerRegisterCard(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CardControllerRegisterCardMutationResult = NonNullable<Awaited<ReturnType<typeof cardControllerRegisterCard>>>
    export type CardControllerRegisterCardMutationBody = RegisterCardRequest
    export type CardControllerRegisterCardMutationError = unknown

    export const useCardControllerRegisterCard = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof cardControllerRegisterCard>>, TError,{data: RegisterCardRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof cardControllerRegisterCard>>,
        TError,
        {data: RegisterCardRequest},
        TContext
      > => {

      const mutationOptions = getCardControllerRegisterCardMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    