/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Allta API
 * Allta의 REST API 문서입니다.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  RegisterCarResponse,
  RegisterCardRequest
} from '.././models';

import { customInstance } from '../../libs/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const cardControllerRegisterCard = (
    registerCardRequest: RegisterCardRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<RegisterCarResponse>(
      {url: `/card`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: registerCardRequest, signal
    },
      options);
    }
  


export const getCardControllerRegisterCardMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof cardControllerRegisterCard>>, TError,{data: RegisterCardRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof cardControllerRegisterCard>>, TError,{data: RegisterCardRequest}, TContext> => {

const mutationKey = ['cardControllerRegisterCard'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof cardControllerRegisterCard>>, {data: RegisterCardRequest}> = (props) => {
          const {data} = props ?? {};

          return  cardControllerRegisterCard(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CardControllerRegisterCardMutationResult = NonNullable<Awaited<ReturnType<typeof cardControllerRegisterCard>>>
    export type CardControllerRegisterCardMutationBody = RegisterCardRequest
    export type CardControllerRegisterCardMutationError = unknown

    export const useCardControllerRegisterCard = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof cardControllerRegisterCard>>, TError,{data: RegisterCardRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof cardControllerRegisterCard>>,
        TError,
        {data: RegisterCardRequest},
        TContext
      > => {

      const mutationOptions = getCardControllerRegisterCardMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    