/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Allta API
 * Allta의 REST API 문서입니다.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetNotificationsResponse,
  GetUnreadNotificationsCountResponse,
  NotificationControllerGetNotificationsParams,
  SendNotificationRequest,
  SendNotificationResponse
} from '.././models';

import { customInstance } from '../../libs/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const notificationControllerGetNotifications = (
    params: NotificationControllerGetNotificationsParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetNotificationsResponse>(
      {url: `/notification`, method: 'GET',
        params, signal
    },
      options);
    }
  

export const getNotificationControllerGetNotificationsQueryKey = (params?: NotificationControllerGetNotificationsParams,) => {
    return [`/notification`, ...(params ? [params]: [])] as const;
    }

    
export const getNotificationControllerGetNotificationsQueryOptions = <TData = Awaited<ReturnType<typeof notificationControllerGetNotifications>>, TError = unknown>(params: NotificationControllerGetNotificationsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof notificationControllerGetNotifications>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getNotificationControllerGetNotificationsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof notificationControllerGetNotifications>>> = ({ signal }) => notificationControllerGetNotifications(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof notificationControllerGetNotifications>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type NotificationControllerGetNotificationsQueryResult = NonNullable<Awaited<ReturnType<typeof notificationControllerGetNotifications>>>
export type NotificationControllerGetNotificationsQueryError = unknown


export function useNotificationControllerGetNotifications<TData = Awaited<ReturnType<typeof notificationControllerGetNotifications>>, TError = unknown>(
 params: NotificationControllerGetNotificationsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof notificationControllerGetNotifications>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof notificationControllerGetNotifications>>,
          TError,
          Awaited<ReturnType<typeof notificationControllerGetNotifications>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useNotificationControllerGetNotifications<TData = Awaited<ReturnType<typeof notificationControllerGetNotifications>>, TError = unknown>(
 params: NotificationControllerGetNotificationsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof notificationControllerGetNotifications>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof notificationControllerGetNotifications>>,
          TError,
          Awaited<ReturnType<typeof notificationControllerGetNotifications>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useNotificationControllerGetNotifications<TData = Awaited<ReturnType<typeof notificationControllerGetNotifications>>, TError = unknown>(
 params: NotificationControllerGetNotificationsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof notificationControllerGetNotifications>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useNotificationControllerGetNotifications<TData = Awaited<ReturnType<typeof notificationControllerGetNotifications>>, TError = unknown>(
 params: NotificationControllerGetNotificationsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof notificationControllerGetNotifications>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getNotificationControllerGetNotificationsQueryOptions(params,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const notificationControllerGetUnreadNotificationsCount = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetUnreadNotificationsCountResponse>(
      {url: `/notification/unread-count`, method: 'GET', signal
    },
      options);
    }
  

export const getNotificationControllerGetUnreadNotificationsCountQueryKey = () => {
    return [`/notification/unread-count`] as const;
    }

    
export const getNotificationControllerGetUnreadNotificationsCountQueryOptions = <TData = Awaited<ReturnType<typeof notificationControllerGetUnreadNotificationsCount>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof notificationControllerGetUnreadNotificationsCount>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getNotificationControllerGetUnreadNotificationsCountQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof notificationControllerGetUnreadNotificationsCount>>> = ({ signal }) => notificationControllerGetUnreadNotificationsCount(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof notificationControllerGetUnreadNotificationsCount>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type NotificationControllerGetUnreadNotificationsCountQueryResult = NonNullable<Awaited<ReturnType<typeof notificationControllerGetUnreadNotificationsCount>>>
export type NotificationControllerGetUnreadNotificationsCountQueryError = unknown


export function useNotificationControllerGetUnreadNotificationsCount<TData = Awaited<ReturnType<typeof notificationControllerGetUnreadNotificationsCount>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof notificationControllerGetUnreadNotificationsCount>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof notificationControllerGetUnreadNotificationsCount>>,
          TError,
          Awaited<ReturnType<typeof notificationControllerGetUnreadNotificationsCount>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useNotificationControllerGetUnreadNotificationsCount<TData = Awaited<ReturnType<typeof notificationControllerGetUnreadNotificationsCount>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof notificationControllerGetUnreadNotificationsCount>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof notificationControllerGetUnreadNotificationsCount>>,
          TError,
          Awaited<ReturnType<typeof notificationControllerGetUnreadNotificationsCount>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useNotificationControllerGetUnreadNotificationsCount<TData = Awaited<ReturnType<typeof notificationControllerGetUnreadNotificationsCount>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof notificationControllerGetUnreadNotificationsCount>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useNotificationControllerGetUnreadNotificationsCount<TData = Awaited<ReturnType<typeof notificationControllerGetUnreadNotificationsCount>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof notificationControllerGetUnreadNotificationsCount>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getNotificationControllerGetUnreadNotificationsCountQueryOptions(options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const notificationControllerSendNotification = (
    sendNotificationRequest: SendNotificationRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<SendNotificationResponse>(
      {url: `/notification/send`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: sendNotificationRequest, signal
    },
      options);
    }
  


export const getNotificationControllerSendNotificationMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof notificationControllerSendNotification>>, TError,{data: SendNotificationRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof notificationControllerSendNotification>>, TError,{data: SendNotificationRequest}, TContext> => {

const mutationKey = ['notificationControllerSendNotification'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof notificationControllerSendNotification>>, {data: SendNotificationRequest}> = (props) => {
          const {data} = props ?? {};

          return  notificationControllerSendNotification(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type NotificationControllerSendNotificationMutationResult = NonNullable<Awaited<ReturnType<typeof notificationControllerSendNotification>>>
    export type NotificationControllerSendNotificationMutationBody = SendNotificationRequest
    export type NotificationControllerSendNotificationMutationError = unknown

    export const useNotificationControllerSendNotification = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof notificationControllerSendNotification>>, TError,{data: SendNotificationRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof notificationControllerSendNotification>>,
        TError,
        {data: SendNotificationRequest},
        TContext
      > => {

      const mutationOptions = getNotificationControllerSendNotificationMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    export const notificationControllerReadNotifications = (
    
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<SendNotificationResponse>(
      {url: `/notification/read`, method: 'PATCH'
    },
      options);
    }
  


export const getNotificationControllerReadNotificationsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof notificationControllerReadNotifications>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof notificationControllerReadNotifications>>, TError,void, TContext> => {

const mutationKey = ['notificationControllerReadNotifications'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof notificationControllerReadNotifications>>, void> = () => {
          

          return  notificationControllerReadNotifications(requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type NotificationControllerReadNotificationsMutationResult = NonNullable<Awaited<ReturnType<typeof notificationControllerReadNotifications>>>
    
    export type NotificationControllerReadNotificationsMutationError = unknown

    export const useNotificationControllerReadNotifications = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof notificationControllerReadNotifications>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof notificationControllerReadNotifications>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getNotificationControllerReadNotificationsMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    