/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Allta API
 * Allta의 REST API 문서입니다.
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AlarmControllerGetManyAlarmsParams
} from '.././models';

import { customInstance } from '../../libs/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const alarmControllerGetManyAlarms = (
    params: AlarmControllerGetManyAlarmsParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<null>(
      {url: `/alarm`, method: 'GET',
        params, signal
    },
      options);
    }
  

export const getAlarmControllerGetManyAlarmsQueryKey = (params?: AlarmControllerGetManyAlarmsParams,) => {
    return [`/alarm`, ...(params ? [params]: [])] as const;
    }

    
export const getAlarmControllerGetManyAlarmsQueryOptions = <TData = Awaited<ReturnType<typeof alarmControllerGetManyAlarms>>, TError = unknown>(params: AlarmControllerGetManyAlarmsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof alarmControllerGetManyAlarms>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAlarmControllerGetManyAlarmsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof alarmControllerGetManyAlarms>>> = ({ signal }) => alarmControllerGetManyAlarms(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof alarmControllerGetManyAlarms>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AlarmControllerGetManyAlarmsQueryResult = NonNullable<Awaited<ReturnType<typeof alarmControllerGetManyAlarms>>>
export type AlarmControllerGetManyAlarmsQueryError = unknown


export function useAlarmControllerGetManyAlarms<TData = Awaited<ReturnType<typeof alarmControllerGetManyAlarms>>, TError = unknown>(
 params: AlarmControllerGetManyAlarmsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof alarmControllerGetManyAlarms>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof alarmControllerGetManyAlarms>>,
          TError,
          Awaited<ReturnType<typeof alarmControllerGetManyAlarms>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAlarmControllerGetManyAlarms<TData = Awaited<ReturnType<typeof alarmControllerGetManyAlarms>>, TError = unknown>(
 params: AlarmControllerGetManyAlarmsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof alarmControllerGetManyAlarms>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof alarmControllerGetManyAlarms>>,
          TError,
          Awaited<ReturnType<typeof alarmControllerGetManyAlarms>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAlarmControllerGetManyAlarms<TData = Awaited<ReturnType<typeof alarmControllerGetManyAlarms>>, TError = unknown>(
 params: AlarmControllerGetManyAlarmsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof alarmControllerGetManyAlarms>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useAlarmControllerGetManyAlarms<TData = Awaited<ReturnType<typeof alarmControllerGetManyAlarms>>, TError = unknown>(
 params: AlarmControllerGetManyAlarmsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof alarmControllerGetManyAlarms>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAlarmControllerGetManyAlarmsQueryOptions(params,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const alarmControllerGetUnreadAlarmCount = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<number>(
      {url: `/alarm/unread/count`, method: 'GET', signal
    },
      options);
    }
  

export const getAlarmControllerGetUnreadAlarmCountQueryKey = () => {
    return [`/alarm/unread/count`] as const;
    }

    
export const getAlarmControllerGetUnreadAlarmCountQueryOptions = <TData = Awaited<ReturnType<typeof alarmControllerGetUnreadAlarmCount>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof alarmControllerGetUnreadAlarmCount>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAlarmControllerGetUnreadAlarmCountQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof alarmControllerGetUnreadAlarmCount>>> = ({ signal }) => alarmControllerGetUnreadAlarmCount(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof alarmControllerGetUnreadAlarmCount>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AlarmControllerGetUnreadAlarmCountQueryResult = NonNullable<Awaited<ReturnType<typeof alarmControllerGetUnreadAlarmCount>>>
export type AlarmControllerGetUnreadAlarmCountQueryError = unknown


export function useAlarmControllerGetUnreadAlarmCount<TData = Awaited<ReturnType<typeof alarmControllerGetUnreadAlarmCount>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof alarmControllerGetUnreadAlarmCount>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof alarmControllerGetUnreadAlarmCount>>,
          TError,
          Awaited<ReturnType<typeof alarmControllerGetUnreadAlarmCount>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAlarmControllerGetUnreadAlarmCount<TData = Awaited<ReturnType<typeof alarmControllerGetUnreadAlarmCount>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof alarmControllerGetUnreadAlarmCount>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof alarmControllerGetUnreadAlarmCount>>,
          TError,
          Awaited<ReturnType<typeof alarmControllerGetUnreadAlarmCount>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAlarmControllerGetUnreadAlarmCount<TData = Awaited<ReturnType<typeof alarmControllerGetUnreadAlarmCount>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof alarmControllerGetUnreadAlarmCount>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useAlarmControllerGetUnreadAlarmCount<TData = Awaited<ReturnType<typeof alarmControllerGetUnreadAlarmCount>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof alarmControllerGetUnreadAlarmCount>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAlarmControllerGetUnreadAlarmCountQueryOptions(options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



