/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Allta API
 * Allta API 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetNoticeDetailResponse,
  GetNoticeListResponse,
  NoticeControllerGetNoticeListParams
} from '.././models';

import { customInstance } from '../../libs/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const noticeControllerGetNoticeList = (
    params: NoticeControllerGetNoticeListParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetNoticeListResponse>(
      {url: `/notice`, method: 'GET',
        params, signal
    },
      options);
    }
  

export const getNoticeControllerGetNoticeListQueryKey = (params?: NoticeControllerGetNoticeListParams,) => {
    return [`/notice`, ...(params ? [params]: [])] as const;
    }

    
export const getNoticeControllerGetNoticeListQueryOptions = <TData = Awaited<ReturnType<typeof noticeControllerGetNoticeList>>, TError = unknown>(params: NoticeControllerGetNoticeListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof noticeControllerGetNoticeList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getNoticeControllerGetNoticeListQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof noticeControllerGetNoticeList>>> = ({ signal }) => noticeControllerGetNoticeList(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof noticeControllerGetNoticeList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type NoticeControllerGetNoticeListQueryResult = NonNullable<Awaited<ReturnType<typeof noticeControllerGetNoticeList>>>
export type NoticeControllerGetNoticeListQueryError = unknown


export function useNoticeControllerGetNoticeList<TData = Awaited<ReturnType<typeof noticeControllerGetNoticeList>>, TError = unknown>(
 params: NoticeControllerGetNoticeListParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof noticeControllerGetNoticeList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof noticeControllerGetNoticeList>>,
          TError,
          Awaited<ReturnType<typeof noticeControllerGetNoticeList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useNoticeControllerGetNoticeList<TData = Awaited<ReturnType<typeof noticeControllerGetNoticeList>>, TError = unknown>(
 params: NoticeControllerGetNoticeListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof noticeControllerGetNoticeList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof noticeControllerGetNoticeList>>,
          TError,
          Awaited<ReturnType<typeof noticeControllerGetNoticeList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useNoticeControllerGetNoticeList<TData = Awaited<ReturnType<typeof noticeControllerGetNoticeList>>, TError = unknown>(
 params: NoticeControllerGetNoticeListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof noticeControllerGetNoticeList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useNoticeControllerGetNoticeList<TData = Awaited<ReturnType<typeof noticeControllerGetNoticeList>>, TError = unknown>(
 params: NoticeControllerGetNoticeListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof noticeControllerGetNoticeList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getNoticeControllerGetNoticeListQueryOptions(params,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const noticeControllerGetNoticeDetail = (
    id: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetNoticeDetailResponse>(
      {url: `/notice/${id}`, method: 'GET', signal
    },
      options);
    }
  

export const getNoticeControllerGetNoticeDetailQueryKey = (id?: string,) => {
    return [`/notice/${id}`] as const;
    }

    
export const getNoticeControllerGetNoticeDetailQueryOptions = <TData = Awaited<ReturnType<typeof noticeControllerGetNoticeDetail>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof noticeControllerGetNoticeDetail>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getNoticeControllerGetNoticeDetailQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof noticeControllerGetNoticeDetail>>> = ({ signal }) => noticeControllerGetNoticeDetail(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof noticeControllerGetNoticeDetail>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type NoticeControllerGetNoticeDetailQueryResult = NonNullable<Awaited<ReturnType<typeof noticeControllerGetNoticeDetail>>>
export type NoticeControllerGetNoticeDetailQueryError = unknown


export function useNoticeControllerGetNoticeDetail<TData = Awaited<ReturnType<typeof noticeControllerGetNoticeDetail>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof noticeControllerGetNoticeDetail>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof noticeControllerGetNoticeDetail>>,
          TError,
          Awaited<ReturnType<typeof noticeControllerGetNoticeDetail>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useNoticeControllerGetNoticeDetail<TData = Awaited<ReturnType<typeof noticeControllerGetNoticeDetail>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof noticeControllerGetNoticeDetail>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof noticeControllerGetNoticeDetail>>,
          TError,
          Awaited<ReturnType<typeof noticeControllerGetNoticeDetail>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useNoticeControllerGetNoticeDetail<TData = Awaited<ReturnType<typeof noticeControllerGetNoticeDetail>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof noticeControllerGetNoticeDetail>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useNoticeControllerGetNoticeDetail<TData = Awaited<ReturnType<typeof noticeControllerGetNoticeDetail>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof noticeControllerGetNoticeDetail>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getNoticeControllerGetNoticeDetailQueryOptions(id,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



