/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Allta API
 * Allta API 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  DiscontinueSubscriptionRequest,
  DiscontinueSubscriptionResponse,
  GetAvailablePassesResponse,
  GetSubscriptionDetailResponse,
  GetSubscriptionListReponse,
  GetTicketListReponse,
  PassControllerGetAvailablePassesParams,
  PassControllerGetSubscriptionListParams,
  PassControllerGetTicketListParams,
  UseSubscriptionRequest,
  UseSubscriptionResponse,
  UseTicketRequest,
  UseTicketResponse,
  VerifyQrCodeRequest,
  VerifyQrCodeResponse
} from '.././models';

import { customInstance } from '../../libs/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const passControllerGetAvailablePasses = (
    params: PassControllerGetAvailablePassesParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetAvailablePassesResponse>(
      {url: `/pass/available`, method: 'GET',
        params, signal
    },
      options);
    }
  

export const getPassControllerGetAvailablePassesQueryKey = (params?: PassControllerGetAvailablePassesParams,) => {
    return [`/pass/available`, ...(params ? [params]: [])] as const;
    }

    
export const getPassControllerGetAvailablePassesQueryOptions = <TData = Awaited<ReturnType<typeof passControllerGetAvailablePasses>>, TError = unknown>(params: PassControllerGetAvailablePassesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof passControllerGetAvailablePasses>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPassControllerGetAvailablePassesQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof passControllerGetAvailablePasses>>> = ({ signal }) => passControllerGetAvailablePasses(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof passControllerGetAvailablePasses>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PassControllerGetAvailablePassesQueryResult = NonNullable<Awaited<ReturnType<typeof passControllerGetAvailablePasses>>>
export type PassControllerGetAvailablePassesQueryError = unknown


export function usePassControllerGetAvailablePasses<TData = Awaited<ReturnType<typeof passControllerGetAvailablePasses>>, TError = unknown>(
 params: PassControllerGetAvailablePassesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof passControllerGetAvailablePasses>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof passControllerGetAvailablePasses>>,
          TError,
          Awaited<ReturnType<typeof passControllerGetAvailablePasses>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePassControllerGetAvailablePasses<TData = Awaited<ReturnType<typeof passControllerGetAvailablePasses>>, TError = unknown>(
 params: PassControllerGetAvailablePassesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof passControllerGetAvailablePasses>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof passControllerGetAvailablePasses>>,
          TError,
          Awaited<ReturnType<typeof passControllerGetAvailablePasses>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePassControllerGetAvailablePasses<TData = Awaited<ReturnType<typeof passControllerGetAvailablePasses>>, TError = unknown>(
 params: PassControllerGetAvailablePassesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof passControllerGetAvailablePasses>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function usePassControllerGetAvailablePasses<TData = Awaited<ReturnType<typeof passControllerGetAvailablePasses>>, TError = unknown>(
 params: PassControllerGetAvailablePassesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof passControllerGetAvailablePasses>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPassControllerGetAvailablePassesQueryOptions(params,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const passControllerVerifyQrCode = (
    verifyQrCodeRequest: VerifyQrCodeRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<VerifyQrCodeResponse>(
      {url: `/pass/qr-code/verify`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: verifyQrCodeRequest, signal
    },
      options);
    }
  


export const getPassControllerVerifyQrCodeMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof passControllerVerifyQrCode>>, TError,{data: VerifyQrCodeRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof passControllerVerifyQrCode>>, TError,{data: VerifyQrCodeRequest}, TContext> => {

const mutationKey = ['passControllerVerifyQrCode'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof passControllerVerifyQrCode>>, {data: VerifyQrCodeRequest}> = (props) => {
          const {data} = props ?? {};

          return  passControllerVerifyQrCode(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PassControllerVerifyQrCodeMutationResult = NonNullable<Awaited<ReturnType<typeof passControllerVerifyQrCode>>>
    export type PassControllerVerifyQrCodeMutationBody = VerifyQrCodeRequest
    export type PassControllerVerifyQrCodeMutationError = unknown

    export const usePassControllerVerifyQrCode = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof passControllerVerifyQrCode>>, TError,{data: VerifyQrCodeRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof passControllerVerifyQrCode>>,
        TError,
        {data: VerifyQrCodeRequest},
        TContext
      > => {

      const mutationOptions = getPassControllerVerifyQrCodeMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    export const passControllerGetTicketList = (
    params: PassControllerGetTicketListParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetTicketListReponse>(
      {url: `/pass/ticket`, method: 'GET',
        params, signal
    },
      options);
    }
  

export const getPassControllerGetTicketListQueryKey = (params?: PassControllerGetTicketListParams,) => {
    return [`/pass/ticket`, ...(params ? [params]: [])] as const;
    }

    
export const getPassControllerGetTicketListQueryOptions = <TData = Awaited<ReturnType<typeof passControllerGetTicketList>>, TError = unknown>(params: PassControllerGetTicketListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof passControllerGetTicketList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPassControllerGetTicketListQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof passControllerGetTicketList>>> = ({ signal }) => passControllerGetTicketList(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof passControllerGetTicketList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PassControllerGetTicketListQueryResult = NonNullable<Awaited<ReturnType<typeof passControllerGetTicketList>>>
export type PassControllerGetTicketListQueryError = unknown


export function usePassControllerGetTicketList<TData = Awaited<ReturnType<typeof passControllerGetTicketList>>, TError = unknown>(
 params: PassControllerGetTicketListParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof passControllerGetTicketList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof passControllerGetTicketList>>,
          TError,
          Awaited<ReturnType<typeof passControllerGetTicketList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePassControllerGetTicketList<TData = Awaited<ReturnType<typeof passControllerGetTicketList>>, TError = unknown>(
 params: PassControllerGetTicketListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof passControllerGetTicketList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof passControllerGetTicketList>>,
          TError,
          Awaited<ReturnType<typeof passControllerGetTicketList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePassControllerGetTicketList<TData = Awaited<ReturnType<typeof passControllerGetTicketList>>, TError = unknown>(
 params: PassControllerGetTicketListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof passControllerGetTicketList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function usePassControllerGetTicketList<TData = Awaited<ReturnType<typeof passControllerGetTicketList>>, TError = unknown>(
 params: PassControllerGetTicketListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof passControllerGetTicketList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPassControllerGetTicketListQueryOptions(params,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const passControllerUseTicket = (
    useTicketRequest: UseTicketRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<UseTicketResponse>(
      {url: `/pass/ticket/use`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: useTicketRequest, signal
    },
      options);
    }
  


export const getPassControllerUseTicketMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof passControllerUseTicket>>, TError,{data: UseTicketRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof passControllerUseTicket>>, TError,{data: UseTicketRequest}, TContext> => {

const mutationKey = ['passControllerUseTicket'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof passControllerUseTicket>>, {data: UseTicketRequest}> = (props) => {
          const {data} = props ?? {};

          return  passControllerUseTicket(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PassControllerUseTicketMutationResult = NonNullable<Awaited<ReturnType<typeof passControllerUseTicket>>>
    export type PassControllerUseTicketMutationBody = UseTicketRequest
    export type PassControllerUseTicketMutationError = unknown

    export const usePassControllerUseTicket = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof passControllerUseTicket>>, TError,{data: UseTicketRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof passControllerUseTicket>>,
        TError,
        {data: UseTicketRequest},
        TContext
      > => {

      const mutationOptions = getPassControllerUseTicketMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    export const passControllerGetSubscriptionList = (
    params: PassControllerGetSubscriptionListParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetSubscriptionListReponse>(
      {url: `/pass/subscription`, method: 'GET',
        params, signal
    },
      options);
    }
  

export const getPassControllerGetSubscriptionListQueryKey = (params?: PassControllerGetSubscriptionListParams,) => {
    return [`/pass/subscription`, ...(params ? [params]: [])] as const;
    }

    
export const getPassControllerGetSubscriptionListQueryOptions = <TData = Awaited<ReturnType<typeof passControllerGetSubscriptionList>>, TError = unknown>(params: PassControllerGetSubscriptionListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof passControllerGetSubscriptionList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPassControllerGetSubscriptionListQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof passControllerGetSubscriptionList>>> = ({ signal }) => passControllerGetSubscriptionList(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof passControllerGetSubscriptionList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PassControllerGetSubscriptionListQueryResult = NonNullable<Awaited<ReturnType<typeof passControllerGetSubscriptionList>>>
export type PassControllerGetSubscriptionListQueryError = unknown


export function usePassControllerGetSubscriptionList<TData = Awaited<ReturnType<typeof passControllerGetSubscriptionList>>, TError = unknown>(
 params: PassControllerGetSubscriptionListParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof passControllerGetSubscriptionList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof passControllerGetSubscriptionList>>,
          TError,
          Awaited<ReturnType<typeof passControllerGetSubscriptionList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePassControllerGetSubscriptionList<TData = Awaited<ReturnType<typeof passControllerGetSubscriptionList>>, TError = unknown>(
 params: PassControllerGetSubscriptionListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof passControllerGetSubscriptionList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof passControllerGetSubscriptionList>>,
          TError,
          Awaited<ReturnType<typeof passControllerGetSubscriptionList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePassControllerGetSubscriptionList<TData = Awaited<ReturnType<typeof passControllerGetSubscriptionList>>, TError = unknown>(
 params: PassControllerGetSubscriptionListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof passControllerGetSubscriptionList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function usePassControllerGetSubscriptionList<TData = Awaited<ReturnType<typeof passControllerGetSubscriptionList>>, TError = unknown>(
 params: PassControllerGetSubscriptionListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof passControllerGetSubscriptionList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPassControllerGetSubscriptionListQueryOptions(params,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const passControllerUseSubscription = (
    useSubscriptionRequest: UseSubscriptionRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<UseSubscriptionResponse>(
      {url: `/pass/subscription/use`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: useSubscriptionRequest, signal
    },
      options);
    }
  


export const getPassControllerUseSubscriptionMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof passControllerUseSubscription>>, TError,{data: UseSubscriptionRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof passControllerUseSubscription>>, TError,{data: UseSubscriptionRequest}, TContext> => {

const mutationKey = ['passControllerUseSubscription'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof passControllerUseSubscription>>, {data: UseSubscriptionRequest}> = (props) => {
          const {data} = props ?? {};

          return  passControllerUseSubscription(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PassControllerUseSubscriptionMutationResult = NonNullable<Awaited<ReturnType<typeof passControllerUseSubscription>>>
    export type PassControllerUseSubscriptionMutationBody = UseSubscriptionRequest
    export type PassControllerUseSubscriptionMutationError = unknown

    export const usePassControllerUseSubscription = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof passControllerUseSubscription>>, TError,{data: UseSubscriptionRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof passControllerUseSubscription>>,
        TError,
        {data: UseSubscriptionRequest},
        TContext
      > => {

      const mutationOptions = getPassControllerUseSubscriptionMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    export const passControllerDiscontinueSubscription = (
    discontinueSubscriptionRequest: DiscontinueSubscriptionRequest,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<DiscontinueSubscriptionResponse>(
      {url: `/pass/subscription/use`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: discontinueSubscriptionRequest
    },
      options);
    }
  


export const getPassControllerDiscontinueSubscriptionMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof passControllerDiscontinueSubscription>>, TError,{data: DiscontinueSubscriptionRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof passControllerDiscontinueSubscription>>, TError,{data: DiscontinueSubscriptionRequest}, TContext> => {

const mutationKey = ['passControllerDiscontinueSubscription'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof passControllerDiscontinueSubscription>>, {data: DiscontinueSubscriptionRequest}> = (props) => {
          const {data} = props ?? {};

          return  passControllerDiscontinueSubscription(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PassControllerDiscontinueSubscriptionMutationResult = NonNullable<Awaited<ReturnType<typeof passControllerDiscontinueSubscription>>>
    export type PassControllerDiscontinueSubscriptionMutationBody = DiscontinueSubscriptionRequest
    export type PassControllerDiscontinueSubscriptionMutationError = unknown

    export const usePassControllerDiscontinueSubscription = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof passControllerDiscontinueSubscription>>, TError,{data: DiscontinueSubscriptionRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof passControllerDiscontinueSubscription>>,
        TError,
        {data: DiscontinueSubscriptionRequest},
        TContext
      > => {

      const mutationOptions = getPassControllerDiscontinueSubscriptionMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    export const passControllerGetSubscriptionDetail = (
    id: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetSubscriptionDetailResponse>(
      {url: `/pass/subscription/${id}`, method: 'GET', signal
    },
      options);
    }
  

export const getPassControllerGetSubscriptionDetailQueryKey = (id?: string,) => {
    return [`/pass/subscription/${id}`] as const;
    }

    
export const getPassControllerGetSubscriptionDetailQueryOptions = <TData = Awaited<ReturnType<typeof passControllerGetSubscriptionDetail>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof passControllerGetSubscriptionDetail>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPassControllerGetSubscriptionDetailQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof passControllerGetSubscriptionDetail>>> = ({ signal }) => passControllerGetSubscriptionDetail(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof passControllerGetSubscriptionDetail>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PassControllerGetSubscriptionDetailQueryResult = NonNullable<Awaited<ReturnType<typeof passControllerGetSubscriptionDetail>>>
export type PassControllerGetSubscriptionDetailQueryError = unknown


export function usePassControllerGetSubscriptionDetail<TData = Awaited<ReturnType<typeof passControllerGetSubscriptionDetail>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof passControllerGetSubscriptionDetail>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof passControllerGetSubscriptionDetail>>,
          TError,
          Awaited<ReturnType<typeof passControllerGetSubscriptionDetail>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePassControllerGetSubscriptionDetail<TData = Awaited<ReturnType<typeof passControllerGetSubscriptionDetail>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof passControllerGetSubscriptionDetail>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof passControllerGetSubscriptionDetail>>,
          TError,
          Awaited<ReturnType<typeof passControllerGetSubscriptionDetail>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePassControllerGetSubscriptionDetail<TData = Awaited<ReturnType<typeof passControllerGetSubscriptionDetail>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof passControllerGetSubscriptionDetail>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function usePassControllerGetSubscriptionDetail<TData = Awaited<ReturnType<typeof passControllerGetSubscriptionDetail>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof passControllerGetSubscriptionDetail>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPassControllerGetSubscriptionDetailQueryOptions(id,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



