/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Allta API
 * Allta API 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  PurchasePassRequest,
  PurchasePassResponse
} from '.././models';

import { customInstance } from '../../libs/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const purchaseControllerPurchasePass = (
    purchasePassRequest: PurchasePassRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<PurchasePassResponse>(
      {url: `/purchase/pass`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: purchasePassRequest, signal
    },
      options);
    }
  


export const getPurchaseControllerPurchasePassMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof purchaseControllerPurchasePass>>, TError,{data: PurchasePassRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof purchaseControllerPurchasePass>>, TError,{data: PurchasePassRequest}, TContext> => {

const mutationKey = ['purchaseControllerPurchasePass'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof purchaseControllerPurchasePass>>, {data: PurchasePassRequest}> = (props) => {
          const {data} = props ?? {};

          return  purchaseControllerPurchasePass(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PurchaseControllerPurchasePassMutationResult = NonNullable<Awaited<ReturnType<typeof purchaseControllerPurchasePass>>>
    export type PurchaseControllerPurchasePassMutationBody = PurchasePassRequest
    export type PurchaseControllerPurchasePassMutationError = unknown

    export const usePurchaseControllerPurchasePass = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof purchaseControllerPurchasePass>>, TError,{data: PurchasePassRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof purchaseControllerPurchasePass>>,
        TError,
        {data: PurchasePassRequest},
        TContext
      > => {

      const mutationOptions = getPurchaseControllerPurchasePassMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    