/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta API
 * Allta API 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetPurchaseDetailResponse,
  GetPurchaseListResponse,
  PurchaseControllerGetPurchaseListParams,
  PurchasePassRequest,
  PurchasePassResponse
} from '.././models';

import { customInstance } from '../../libs/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const purchaseControllerGetPurchaseList = (
    params: PurchaseControllerGetPurchaseListParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetPurchaseListResponse>(
      {url: `/purchase`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getPurchaseControllerGetPurchaseListQueryKey = (params?: PurchaseControllerGetPurchaseListParams,) => {
    return [
    `/purchase`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getPurchaseControllerGetPurchaseListQueryOptions = <TData = Awaited<ReturnType<typeof purchaseControllerGetPurchaseList>>, TError = unknown>(params: PurchaseControllerGetPurchaseListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof purchaseControllerGetPurchaseList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPurchaseControllerGetPurchaseListQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof purchaseControllerGetPurchaseList>>> = ({ signal }) => purchaseControllerGetPurchaseList(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof purchaseControllerGetPurchaseList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PurchaseControllerGetPurchaseListQueryResult = NonNullable<Awaited<ReturnType<typeof purchaseControllerGetPurchaseList>>>
export type PurchaseControllerGetPurchaseListQueryError = unknown


export function usePurchaseControllerGetPurchaseList<TData = Awaited<ReturnType<typeof purchaseControllerGetPurchaseList>>, TError = unknown>(
 params: PurchaseControllerGetPurchaseListParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof purchaseControllerGetPurchaseList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof purchaseControllerGetPurchaseList>>,
          TError,
          Awaited<ReturnType<typeof purchaseControllerGetPurchaseList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePurchaseControllerGetPurchaseList<TData = Awaited<ReturnType<typeof purchaseControllerGetPurchaseList>>, TError = unknown>(
 params: PurchaseControllerGetPurchaseListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof purchaseControllerGetPurchaseList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof purchaseControllerGetPurchaseList>>,
          TError,
          Awaited<ReturnType<typeof purchaseControllerGetPurchaseList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePurchaseControllerGetPurchaseList<TData = Awaited<ReturnType<typeof purchaseControllerGetPurchaseList>>, TError = unknown>(
 params: PurchaseControllerGetPurchaseListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof purchaseControllerGetPurchaseList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function usePurchaseControllerGetPurchaseList<TData = Awaited<ReturnType<typeof purchaseControllerGetPurchaseList>>, TError = unknown>(
 params: PurchaseControllerGetPurchaseListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof purchaseControllerGetPurchaseList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPurchaseControllerGetPurchaseListQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const purchaseControllerGetPurchaseDetail = (
    id: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetPurchaseDetailResponse>(
      {url: `/purchase/${id}`, method: 'GET', signal
    },
      options);
    }
  



export const getPurchaseControllerGetPurchaseDetailQueryKey = (id?: string,) => {
    return [
    `/purchase/${id}`
    ] as const;
    }

    
export const getPurchaseControllerGetPurchaseDetailQueryOptions = <TData = Awaited<ReturnType<typeof purchaseControllerGetPurchaseDetail>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof purchaseControllerGetPurchaseDetail>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPurchaseControllerGetPurchaseDetailQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof purchaseControllerGetPurchaseDetail>>> = ({ signal }) => purchaseControllerGetPurchaseDetail(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof purchaseControllerGetPurchaseDetail>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PurchaseControllerGetPurchaseDetailQueryResult = NonNullable<Awaited<ReturnType<typeof purchaseControllerGetPurchaseDetail>>>
export type PurchaseControllerGetPurchaseDetailQueryError = unknown


export function usePurchaseControllerGetPurchaseDetail<TData = Awaited<ReturnType<typeof purchaseControllerGetPurchaseDetail>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof purchaseControllerGetPurchaseDetail>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof purchaseControllerGetPurchaseDetail>>,
          TError,
          Awaited<ReturnType<typeof purchaseControllerGetPurchaseDetail>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePurchaseControllerGetPurchaseDetail<TData = Awaited<ReturnType<typeof purchaseControllerGetPurchaseDetail>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof purchaseControllerGetPurchaseDetail>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof purchaseControllerGetPurchaseDetail>>,
          TError,
          Awaited<ReturnType<typeof purchaseControllerGetPurchaseDetail>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePurchaseControllerGetPurchaseDetail<TData = Awaited<ReturnType<typeof purchaseControllerGetPurchaseDetail>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof purchaseControllerGetPurchaseDetail>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function usePurchaseControllerGetPurchaseDetail<TData = Awaited<ReturnType<typeof purchaseControllerGetPurchaseDetail>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof purchaseControllerGetPurchaseDetail>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPurchaseControllerGetPurchaseDetailQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const purchaseControllerPurchasePass = (
    purchasePassRequest: PurchasePassRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<PurchasePassResponse>(
      {url: `/purchase/pass`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: purchasePassRequest, signal
    },
      options);
    }
  


export const getPurchaseControllerPurchasePassMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof purchaseControllerPurchasePass>>, TError,{data: PurchasePassRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof purchaseControllerPurchasePass>>, TError,{data: PurchasePassRequest}, TContext> => {

const mutationKey = ['purchaseControllerPurchasePass'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof purchaseControllerPurchasePass>>, {data: PurchasePassRequest}> = (props) => {
          const {data} = props ?? {};

          return  purchaseControllerPurchasePass(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PurchaseControllerPurchasePassMutationResult = NonNullable<Awaited<ReturnType<typeof purchaseControllerPurchasePass>>>
    export type PurchaseControllerPurchasePassMutationBody = PurchasePassRequest
    export type PurchaseControllerPurchasePassMutationError = unknown

    export const usePurchaseControllerPurchasePass = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof purchaseControllerPurchasePass>>, TError,{data: PurchasePassRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof purchaseControllerPurchasePass>>,
        TError,
        {data: PurchasePassRequest},
        TContext
      > => {

      const mutationOptions = getPurchaseControllerPurchasePassMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    