/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta API
 * Allta API 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetMyStoreListResponse,
  GetStoreDetailResponse,
  GetStoreGroupListResponse,
  GetStoreListForWebResponse,
  GetStoreListResponse,
  StoreControllerGetMyStoreListParams,
  StoreControllerGetStoreGroupListParams,
  StoreControllerGetStoreListForWebParams,
  StoreControllerGetStoreListParams
} from '.././models';

import { customInstance } from '../../libs/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const storeControllerGetStoreList = (
    params: StoreControllerGetStoreListParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetStoreListResponse>(
      {url: `/store`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getStoreControllerGetStoreListQueryKey = (params?: StoreControllerGetStoreListParams,) => {
    return [
    `/store`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getStoreControllerGetStoreListQueryOptions = <TData = Awaited<ReturnType<typeof storeControllerGetStoreList>>, TError = unknown>(params: StoreControllerGetStoreListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof storeControllerGetStoreList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getStoreControllerGetStoreListQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof storeControllerGetStoreList>>> = ({ signal }) => storeControllerGetStoreList(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof storeControllerGetStoreList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type StoreControllerGetStoreListQueryResult = NonNullable<Awaited<ReturnType<typeof storeControllerGetStoreList>>>
export type StoreControllerGetStoreListQueryError = unknown


export function useStoreControllerGetStoreList<TData = Awaited<ReturnType<typeof storeControllerGetStoreList>>, TError = unknown>(
 params: StoreControllerGetStoreListParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof storeControllerGetStoreList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof storeControllerGetStoreList>>,
          TError,
          Awaited<ReturnType<typeof storeControllerGetStoreList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useStoreControllerGetStoreList<TData = Awaited<ReturnType<typeof storeControllerGetStoreList>>, TError = unknown>(
 params: StoreControllerGetStoreListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof storeControllerGetStoreList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof storeControllerGetStoreList>>,
          TError,
          Awaited<ReturnType<typeof storeControllerGetStoreList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useStoreControllerGetStoreList<TData = Awaited<ReturnType<typeof storeControllerGetStoreList>>, TError = unknown>(
 params: StoreControllerGetStoreListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof storeControllerGetStoreList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useStoreControllerGetStoreList<TData = Awaited<ReturnType<typeof storeControllerGetStoreList>>, TError = unknown>(
 params: StoreControllerGetStoreListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof storeControllerGetStoreList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getStoreControllerGetStoreListQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const storeControllerGetStoreGroupList = (
    params: StoreControllerGetStoreGroupListParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetStoreGroupListResponse>(
      {url: `/store/groups`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getStoreControllerGetStoreGroupListQueryKey = (params?: StoreControllerGetStoreGroupListParams,) => {
    return [
    `/store/groups`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getStoreControllerGetStoreGroupListQueryOptions = <TData = Awaited<ReturnType<typeof storeControllerGetStoreGroupList>>, TError = unknown>(params: StoreControllerGetStoreGroupListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof storeControllerGetStoreGroupList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getStoreControllerGetStoreGroupListQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof storeControllerGetStoreGroupList>>> = ({ signal }) => storeControllerGetStoreGroupList(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof storeControllerGetStoreGroupList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type StoreControllerGetStoreGroupListQueryResult = NonNullable<Awaited<ReturnType<typeof storeControllerGetStoreGroupList>>>
export type StoreControllerGetStoreGroupListQueryError = unknown


export function useStoreControllerGetStoreGroupList<TData = Awaited<ReturnType<typeof storeControllerGetStoreGroupList>>, TError = unknown>(
 params: StoreControllerGetStoreGroupListParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof storeControllerGetStoreGroupList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof storeControllerGetStoreGroupList>>,
          TError,
          Awaited<ReturnType<typeof storeControllerGetStoreGroupList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useStoreControllerGetStoreGroupList<TData = Awaited<ReturnType<typeof storeControllerGetStoreGroupList>>, TError = unknown>(
 params: StoreControllerGetStoreGroupListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof storeControllerGetStoreGroupList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof storeControllerGetStoreGroupList>>,
          TError,
          Awaited<ReturnType<typeof storeControllerGetStoreGroupList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useStoreControllerGetStoreGroupList<TData = Awaited<ReturnType<typeof storeControllerGetStoreGroupList>>, TError = unknown>(
 params: StoreControllerGetStoreGroupListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof storeControllerGetStoreGroupList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useStoreControllerGetStoreGroupList<TData = Awaited<ReturnType<typeof storeControllerGetStoreGroupList>>, TError = unknown>(
 params: StoreControllerGetStoreGroupListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof storeControllerGetStoreGroupList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getStoreControllerGetStoreGroupListQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const storeControllerGetMyStoreList = (
    params: StoreControllerGetMyStoreListParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetMyStoreListResponse>(
      {url: `/store/my`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getStoreControllerGetMyStoreListQueryKey = (params?: StoreControllerGetMyStoreListParams,) => {
    return [
    `/store/my`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getStoreControllerGetMyStoreListQueryOptions = <TData = Awaited<ReturnType<typeof storeControllerGetMyStoreList>>, TError = unknown>(params: StoreControllerGetMyStoreListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof storeControllerGetMyStoreList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getStoreControllerGetMyStoreListQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof storeControllerGetMyStoreList>>> = ({ signal }) => storeControllerGetMyStoreList(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof storeControllerGetMyStoreList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type StoreControllerGetMyStoreListQueryResult = NonNullable<Awaited<ReturnType<typeof storeControllerGetMyStoreList>>>
export type StoreControllerGetMyStoreListQueryError = unknown


export function useStoreControllerGetMyStoreList<TData = Awaited<ReturnType<typeof storeControllerGetMyStoreList>>, TError = unknown>(
 params: StoreControllerGetMyStoreListParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof storeControllerGetMyStoreList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof storeControllerGetMyStoreList>>,
          TError,
          Awaited<ReturnType<typeof storeControllerGetMyStoreList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useStoreControllerGetMyStoreList<TData = Awaited<ReturnType<typeof storeControllerGetMyStoreList>>, TError = unknown>(
 params: StoreControllerGetMyStoreListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof storeControllerGetMyStoreList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof storeControllerGetMyStoreList>>,
          TError,
          Awaited<ReturnType<typeof storeControllerGetMyStoreList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useStoreControllerGetMyStoreList<TData = Awaited<ReturnType<typeof storeControllerGetMyStoreList>>, TError = unknown>(
 params: StoreControllerGetMyStoreListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof storeControllerGetMyStoreList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useStoreControllerGetMyStoreList<TData = Awaited<ReturnType<typeof storeControllerGetMyStoreList>>, TError = unknown>(
 params: StoreControllerGetMyStoreListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof storeControllerGetMyStoreList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getStoreControllerGetMyStoreListQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const storeControllerGetStoreListForWeb = (
    params: StoreControllerGetStoreListForWebParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetStoreListForWebResponse>(
      {url: `/store/web`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getStoreControllerGetStoreListForWebQueryKey = (params?: StoreControllerGetStoreListForWebParams,) => {
    return [
    `/store/web`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getStoreControllerGetStoreListForWebQueryOptions = <TData = Awaited<ReturnType<typeof storeControllerGetStoreListForWeb>>, TError = unknown>(params: StoreControllerGetStoreListForWebParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof storeControllerGetStoreListForWeb>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getStoreControllerGetStoreListForWebQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof storeControllerGetStoreListForWeb>>> = ({ signal }) => storeControllerGetStoreListForWeb(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof storeControllerGetStoreListForWeb>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type StoreControllerGetStoreListForWebQueryResult = NonNullable<Awaited<ReturnType<typeof storeControllerGetStoreListForWeb>>>
export type StoreControllerGetStoreListForWebQueryError = unknown


export function useStoreControllerGetStoreListForWeb<TData = Awaited<ReturnType<typeof storeControllerGetStoreListForWeb>>, TError = unknown>(
 params: StoreControllerGetStoreListForWebParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof storeControllerGetStoreListForWeb>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof storeControllerGetStoreListForWeb>>,
          TError,
          Awaited<ReturnType<typeof storeControllerGetStoreListForWeb>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useStoreControllerGetStoreListForWeb<TData = Awaited<ReturnType<typeof storeControllerGetStoreListForWeb>>, TError = unknown>(
 params: StoreControllerGetStoreListForWebParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof storeControllerGetStoreListForWeb>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof storeControllerGetStoreListForWeb>>,
          TError,
          Awaited<ReturnType<typeof storeControllerGetStoreListForWeb>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useStoreControllerGetStoreListForWeb<TData = Awaited<ReturnType<typeof storeControllerGetStoreListForWeb>>, TError = unknown>(
 params: StoreControllerGetStoreListForWebParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof storeControllerGetStoreListForWeb>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useStoreControllerGetStoreListForWeb<TData = Awaited<ReturnType<typeof storeControllerGetStoreListForWeb>>, TError = unknown>(
 params: StoreControllerGetStoreListForWebParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof storeControllerGetStoreListForWeb>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getStoreControllerGetStoreListForWebQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const storeControllerGetStoreDetail = (
    id: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetStoreDetailResponse>(
      {url: `/store/${id}`, method: 'GET', signal
    },
      options);
    }
  



export const getStoreControllerGetStoreDetailQueryKey = (id?: string,) => {
    return [
    `/store/${id}`
    ] as const;
    }

    
export const getStoreControllerGetStoreDetailQueryOptions = <TData = Awaited<ReturnType<typeof storeControllerGetStoreDetail>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof storeControllerGetStoreDetail>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getStoreControllerGetStoreDetailQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof storeControllerGetStoreDetail>>> = ({ signal }) => storeControllerGetStoreDetail(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof storeControllerGetStoreDetail>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type StoreControllerGetStoreDetailQueryResult = NonNullable<Awaited<ReturnType<typeof storeControllerGetStoreDetail>>>
export type StoreControllerGetStoreDetailQueryError = unknown


export function useStoreControllerGetStoreDetail<TData = Awaited<ReturnType<typeof storeControllerGetStoreDetail>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof storeControllerGetStoreDetail>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof storeControllerGetStoreDetail>>,
          TError,
          Awaited<ReturnType<typeof storeControllerGetStoreDetail>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useStoreControllerGetStoreDetail<TData = Awaited<ReturnType<typeof storeControllerGetStoreDetail>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof storeControllerGetStoreDetail>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof storeControllerGetStoreDetail>>,
          TError,
          Awaited<ReturnType<typeof storeControllerGetStoreDetail>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useStoreControllerGetStoreDetail<TData = Awaited<ReturnType<typeof storeControllerGetStoreDetail>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof storeControllerGetStoreDetail>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useStoreControllerGetStoreDetail<TData = Awaited<ReturnType<typeof storeControllerGetStoreDetail>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof storeControllerGetStoreDetail>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getStoreControllerGetStoreDetailQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const storeControllerGetStoreDetailForWeb = (
    id: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetStoreDetailResponse>(
      {url: `/store/web/${id}`, method: 'GET', signal
    },
      options);
    }
  



export const getStoreControllerGetStoreDetailForWebQueryKey = (id?: string,) => {
    return [
    `/store/web/${id}`
    ] as const;
    }

    
export const getStoreControllerGetStoreDetailForWebQueryOptions = <TData = Awaited<ReturnType<typeof storeControllerGetStoreDetailForWeb>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof storeControllerGetStoreDetailForWeb>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getStoreControllerGetStoreDetailForWebQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof storeControllerGetStoreDetailForWeb>>> = ({ signal }) => storeControllerGetStoreDetailForWeb(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof storeControllerGetStoreDetailForWeb>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type StoreControllerGetStoreDetailForWebQueryResult = NonNullable<Awaited<ReturnType<typeof storeControllerGetStoreDetailForWeb>>>
export type StoreControllerGetStoreDetailForWebQueryError = unknown


export function useStoreControllerGetStoreDetailForWeb<TData = Awaited<ReturnType<typeof storeControllerGetStoreDetailForWeb>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof storeControllerGetStoreDetailForWeb>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof storeControllerGetStoreDetailForWeb>>,
          TError,
          Awaited<ReturnType<typeof storeControllerGetStoreDetailForWeb>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useStoreControllerGetStoreDetailForWeb<TData = Awaited<ReturnType<typeof storeControllerGetStoreDetailForWeb>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof storeControllerGetStoreDetailForWeb>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof storeControllerGetStoreDetailForWeb>>,
          TError,
          Awaited<ReturnType<typeof storeControllerGetStoreDetailForWeb>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useStoreControllerGetStoreDetailForWeb<TData = Awaited<ReturnType<typeof storeControllerGetStoreDetailForWeb>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof storeControllerGetStoreDetailForWeb>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useStoreControllerGetStoreDetailForWeb<TData = Awaited<ReturnType<typeof storeControllerGetStoreDetailForWeb>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof storeControllerGetStoreDetailForWeb>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getStoreControllerGetStoreDetailForWebQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



