/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Allta API
 * Allta의 REST API 문서입니다.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetStoreDetailResponse,
  GetStoreGroupListResponse,
  GetStoreListResponse,
  RegisterStoreRequest,
  RegisterStoreResponse,
  StoreControllerGetStoreGroupListParams,
  StoreControllerGetStoreListParams
} from '.././models';

import { customInstance } from '../../libs/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const storeControllerGetStoreList = (
    params: StoreControllerGetStoreListParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetStoreListResponse>(
      {url: `/store`, method: 'GET',
        params, signal
    },
      options);
    }
  

export const getStoreControllerGetStoreListQueryKey = (params?: StoreControllerGetStoreListParams,) => {
    return [`/store`, ...(params ? [params]: [])] as const;
    }

    
export const getStoreControllerGetStoreListQueryOptions = <TData = Awaited<ReturnType<typeof storeControllerGetStoreList>>, TError = unknown>(params: StoreControllerGetStoreListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof storeControllerGetStoreList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getStoreControllerGetStoreListQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof storeControllerGetStoreList>>> = ({ signal }) => storeControllerGetStoreList(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof storeControllerGetStoreList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type StoreControllerGetStoreListQueryResult = NonNullable<Awaited<ReturnType<typeof storeControllerGetStoreList>>>
export type StoreControllerGetStoreListQueryError = unknown


export function useStoreControllerGetStoreList<TData = Awaited<ReturnType<typeof storeControllerGetStoreList>>, TError = unknown>(
 params: StoreControllerGetStoreListParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof storeControllerGetStoreList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof storeControllerGetStoreList>>,
          TError,
          Awaited<ReturnType<typeof storeControllerGetStoreList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useStoreControllerGetStoreList<TData = Awaited<ReturnType<typeof storeControllerGetStoreList>>, TError = unknown>(
 params: StoreControllerGetStoreListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof storeControllerGetStoreList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof storeControllerGetStoreList>>,
          TError,
          Awaited<ReturnType<typeof storeControllerGetStoreList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useStoreControllerGetStoreList<TData = Awaited<ReturnType<typeof storeControllerGetStoreList>>, TError = unknown>(
 params: StoreControllerGetStoreListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof storeControllerGetStoreList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useStoreControllerGetStoreList<TData = Awaited<ReturnType<typeof storeControllerGetStoreList>>, TError = unknown>(
 params: StoreControllerGetStoreListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof storeControllerGetStoreList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getStoreControllerGetStoreListQueryOptions(params,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const storeControllerGetStoreDetail = (
    id: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetStoreDetailResponse>(
      {url: `/store/${id}`, method: 'GET', signal
    },
      options);
    }
  

export const getStoreControllerGetStoreDetailQueryKey = (id?: string,) => {
    return [`/store/${id}`] as const;
    }

    
export const getStoreControllerGetStoreDetailQueryOptions = <TData = Awaited<ReturnType<typeof storeControllerGetStoreDetail>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof storeControllerGetStoreDetail>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getStoreControllerGetStoreDetailQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof storeControllerGetStoreDetail>>> = ({ signal }) => storeControllerGetStoreDetail(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof storeControllerGetStoreDetail>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type StoreControllerGetStoreDetailQueryResult = NonNullable<Awaited<ReturnType<typeof storeControllerGetStoreDetail>>>
export type StoreControllerGetStoreDetailQueryError = unknown


export function useStoreControllerGetStoreDetail<TData = Awaited<ReturnType<typeof storeControllerGetStoreDetail>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof storeControllerGetStoreDetail>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof storeControllerGetStoreDetail>>,
          TError,
          Awaited<ReturnType<typeof storeControllerGetStoreDetail>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useStoreControllerGetStoreDetail<TData = Awaited<ReturnType<typeof storeControllerGetStoreDetail>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof storeControllerGetStoreDetail>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof storeControllerGetStoreDetail>>,
          TError,
          Awaited<ReturnType<typeof storeControllerGetStoreDetail>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useStoreControllerGetStoreDetail<TData = Awaited<ReturnType<typeof storeControllerGetStoreDetail>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof storeControllerGetStoreDetail>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useStoreControllerGetStoreDetail<TData = Awaited<ReturnType<typeof storeControllerGetStoreDetail>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof storeControllerGetStoreDetail>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getStoreControllerGetStoreDetailQueryOptions(id,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const storeControllerGetStoreGroupList = (
    params: StoreControllerGetStoreGroupListParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetStoreGroupListResponse>(
      {url: `/store/groups`, method: 'GET',
        params, signal
    },
      options);
    }
  

export const getStoreControllerGetStoreGroupListQueryKey = (params?: StoreControllerGetStoreGroupListParams,) => {
    return [`/store/groups`, ...(params ? [params]: [])] as const;
    }

    
export const getStoreControllerGetStoreGroupListQueryOptions = <TData = Awaited<ReturnType<typeof storeControllerGetStoreGroupList>>, TError = unknown>(params: StoreControllerGetStoreGroupListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof storeControllerGetStoreGroupList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getStoreControllerGetStoreGroupListQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof storeControllerGetStoreGroupList>>> = ({ signal }) => storeControllerGetStoreGroupList(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof storeControllerGetStoreGroupList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type StoreControllerGetStoreGroupListQueryResult = NonNullable<Awaited<ReturnType<typeof storeControllerGetStoreGroupList>>>
export type StoreControllerGetStoreGroupListQueryError = unknown


export function useStoreControllerGetStoreGroupList<TData = Awaited<ReturnType<typeof storeControllerGetStoreGroupList>>, TError = unknown>(
 params: StoreControllerGetStoreGroupListParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof storeControllerGetStoreGroupList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof storeControllerGetStoreGroupList>>,
          TError,
          Awaited<ReturnType<typeof storeControllerGetStoreGroupList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useStoreControllerGetStoreGroupList<TData = Awaited<ReturnType<typeof storeControllerGetStoreGroupList>>, TError = unknown>(
 params: StoreControllerGetStoreGroupListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof storeControllerGetStoreGroupList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof storeControllerGetStoreGroupList>>,
          TError,
          Awaited<ReturnType<typeof storeControllerGetStoreGroupList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useStoreControllerGetStoreGroupList<TData = Awaited<ReturnType<typeof storeControllerGetStoreGroupList>>, TError = unknown>(
 params: StoreControllerGetStoreGroupListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof storeControllerGetStoreGroupList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useStoreControllerGetStoreGroupList<TData = Awaited<ReturnType<typeof storeControllerGetStoreGroupList>>, TError = unknown>(
 params: StoreControllerGetStoreGroupListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof storeControllerGetStoreGroupList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getStoreControllerGetStoreGroupListQueryOptions(params,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const storeControllerRegisterStore = (
    registerStoreRequest: RegisterStoreRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<RegisterStoreResponse>(
      {url: `/store/register`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: registerStoreRequest, signal
    },
      options);
    }
  


export const getStoreControllerRegisterStoreMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof storeControllerRegisterStore>>, TError,{data: RegisterStoreRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof storeControllerRegisterStore>>, TError,{data: RegisterStoreRequest}, TContext> => {

const mutationKey = ['storeControllerRegisterStore'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof storeControllerRegisterStore>>, {data: RegisterStoreRequest}> = (props) => {
          const {data} = props ?? {};

          return  storeControllerRegisterStore(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type StoreControllerRegisterStoreMutationResult = NonNullable<Awaited<ReturnType<typeof storeControllerRegisterStore>>>
    export type StoreControllerRegisterStoreMutationBody = RegisterStoreRequest
    export type StoreControllerRegisterStoreMutationError = unknown

    export const useStoreControllerRegisterStore = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof storeControllerRegisterStore>>, TError,{data: RegisterStoreRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof storeControllerRegisterStore>>,
        TError,
        {data: RegisterStoreRequest},
        TContext
      > => {

      const mutationOptions = getStoreControllerRegisterStoreMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    