/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Allta API
 * Allta의 REST API 문서입니다.
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  StoreControllerGetManyStoresParams
} from '.././models';

import { customInstance } from '../../libs/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const storeControllerGetManyStores = (
    params: StoreControllerGetManyStoresParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<null>(
      {url: `/store`, method: 'GET',
        params, signal
    },
      options);
    }
  

export const getStoreControllerGetManyStoresQueryKey = (params?: StoreControllerGetManyStoresParams,) => {
    return [`/store`, ...(params ? [params]: [])] as const;
    }

    
export const getStoreControllerGetManyStoresQueryOptions = <TData = Awaited<ReturnType<typeof storeControllerGetManyStores>>, TError = unknown>(params: StoreControllerGetManyStoresParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof storeControllerGetManyStores>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getStoreControllerGetManyStoresQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof storeControllerGetManyStores>>> = ({ signal }) => storeControllerGetManyStores(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof storeControllerGetManyStores>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type StoreControllerGetManyStoresQueryResult = NonNullable<Awaited<ReturnType<typeof storeControllerGetManyStores>>>
export type StoreControllerGetManyStoresQueryError = unknown


export function useStoreControllerGetManyStores<TData = Awaited<ReturnType<typeof storeControllerGetManyStores>>, TError = unknown>(
 params: StoreControllerGetManyStoresParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof storeControllerGetManyStores>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof storeControllerGetManyStores>>,
          TError,
          Awaited<ReturnType<typeof storeControllerGetManyStores>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useStoreControllerGetManyStores<TData = Awaited<ReturnType<typeof storeControllerGetManyStores>>, TError = unknown>(
 params: StoreControllerGetManyStoresParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof storeControllerGetManyStores>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof storeControllerGetManyStores>>,
          TError,
          Awaited<ReturnType<typeof storeControllerGetManyStores>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useStoreControllerGetManyStores<TData = Awaited<ReturnType<typeof storeControllerGetManyStores>>, TError = unknown>(
 params: StoreControllerGetManyStoresParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof storeControllerGetManyStores>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useStoreControllerGetManyStores<TData = Awaited<ReturnType<typeof storeControllerGetManyStores>>, TError = unknown>(
 params: StoreControllerGetManyStoresParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof storeControllerGetManyStores>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getStoreControllerGetManyStoresQueryOptions(params,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



