/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta API
 * Allta API 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetSerivceHistoryListResponse,
  ServiceHistoryControllerGetServiceHistoryListParams
} from '.././models';

import { customInstance } from '../../libs/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const serviceHistoryControllerGetServiceHistoryList = (
    params: ServiceHistoryControllerGetServiceHistoryListParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetSerivceHistoryListResponse>(
      {url: `/service-history`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getServiceHistoryControllerGetServiceHistoryListQueryKey = (params?: ServiceHistoryControllerGetServiceHistoryListParams,) => {
    return [
    `/service-history`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getServiceHistoryControllerGetServiceHistoryListQueryOptions = <TData = Awaited<ReturnType<typeof serviceHistoryControllerGetServiceHistoryList>>, TError = unknown>(params: ServiceHistoryControllerGetServiceHistoryListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof serviceHistoryControllerGetServiceHistoryList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getServiceHistoryControllerGetServiceHistoryListQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof serviceHistoryControllerGetServiceHistoryList>>> = ({ signal }) => serviceHistoryControllerGetServiceHistoryList(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof serviceHistoryControllerGetServiceHistoryList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ServiceHistoryControllerGetServiceHistoryListQueryResult = NonNullable<Awaited<ReturnType<typeof serviceHistoryControllerGetServiceHistoryList>>>
export type ServiceHistoryControllerGetServiceHistoryListQueryError = unknown


export function useServiceHistoryControllerGetServiceHistoryList<TData = Awaited<ReturnType<typeof serviceHistoryControllerGetServiceHistoryList>>, TError = unknown>(
 params: ServiceHistoryControllerGetServiceHistoryListParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof serviceHistoryControllerGetServiceHistoryList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof serviceHistoryControllerGetServiceHistoryList>>,
          TError,
          Awaited<ReturnType<typeof serviceHistoryControllerGetServiceHistoryList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useServiceHistoryControllerGetServiceHistoryList<TData = Awaited<ReturnType<typeof serviceHistoryControllerGetServiceHistoryList>>, TError = unknown>(
 params: ServiceHistoryControllerGetServiceHistoryListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof serviceHistoryControllerGetServiceHistoryList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof serviceHistoryControllerGetServiceHistoryList>>,
          TError,
          Awaited<ReturnType<typeof serviceHistoryControllerGetServiceHistoryList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useServiceHistoryControllerGetServiceHistoryList<TData = Awaited<ReturnType<typeof serviceHistoryControllerGetServiceHistoryList>>, TError = unknown>(
 params: ServiceHistoryControllerGetServiceHistoryListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof serviceHistoryControllerGetServiceHistoryList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useServiceHistoryControllerGetServiceHistoryList<TData = Awaited<ReturnType<typeof serviceHistoryControllerGetServiceHistoryList>>, TError = unknown>(
 params: ServiceHistoryControllerGetServiceHistoryListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof serviceHistoryControllerGetServiceHistoryList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getServiceHistoryControllerGetServiceHistoryListQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



