/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Allta API
 * Allta API 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ChangeMainCarRequest,
  ChangeMainCarResponse,
  DeleteCarRequest,
  DeleteCarResponse,
  GetCarListResponse,
  GetCarModelsResponse,
  GetCarVendorsResponse,
  RegisterCarRequest,
  RegisterCarResponse,
  UpdateCarRequest,
  UpdateCarResponse
} from '.././models';

import { customInstance } from '../../libs/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const carControllerGetCarList = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetCarListResponse>(
      {url: `/car`, method: 'GET', signal
    },
      options);
    }
  

export const getCarControllerGetCarListQueryKey = () => {
    return [`/car`] as const;
    }

    
export const getCarControllerGetCarListQueryOptions = <TData = Awaited<ReturnType<typeof carControllerGetCarList>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof carControllerGetCarList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCarControllerGetCarListQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof carControllerGetCarList>>> = ({ signal }) => carControllerGetCarList(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof carControllerGetCarList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CarControllerGetCarListQueryResult = NonNullable<Awaited<ReturnType<typeof carControllerGetCarList>>>
export type CarControllerGetCarListQueryError = unknown


export function useCarControllerGetCarList<TData = Awaited<ReturnType<typeof carControllerGetCarList>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof carControllerGetCarList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof carControllerGetCarList>>,
          TError,
          Awaited<ReturnType<typeof carControllerGetCarList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCarControllerGetCarList<TData = Awaited<ReturnType<typeof carControllerGetCarList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof carControllerGetCarList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof carControllerGetCarList>>,
          TError,
          Awaited<ReturnType<typeof carControllerGetCarList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCarControllerGetCarList<TData = Awaited<ReturnType<typeof carControllerGetCarList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof carControllerGetCarList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useCarControllerGetCarList<TData = Awaited<ReturnType<typeof carControllerGetCarList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof carControllerGetCarList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCarControllerGetCarListQueryOptions(options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const carControllerRegisterCar = (
    registerCarRequest: RegisterCarRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<RegisterCarResponse>(
      {url: `/car`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: registerCarRequest, signal
    },
      options);
    }
  


export const getCarControllerRegisterCarMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof carControllerRegisterCar>>, TError,{data: RegisterCarRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof carControllerRegisterCar>>, TError,{data: RegisterCarRequest}, TContext> => {

const mutationKey = ['carControllerRegisterCar'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof carControllerRegisterCar>>, {data: RegisterCarRequest}> = (props) => {
          const {data} = props ?? {};

          return  carControllerRegisterCar(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CarControllerRegisterCarMutationResult = NonNullable<Awaited<ReturnType<typeof carControllerRegisterCar>>>
    export type CarControllerRegisterCarMutationBody = RegisterCarRequest
    export type CarControllerRegisterCarMutationError = unknown

    export const useCarControllerRegisterCar = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof carControllerRegisterCar>>, TError,{data: RegisterCarRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof carControllerRegisterCar>>,
        TError,
        {data: RegisterCarRequest},
        TContext
      > => {

      const mutationOptions = getCarControllerRegisterCarMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    export const carControllerDeleteCar = (
    deleteCarRequest: DeleteCarRequest,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<DeleteCarResponse>(
      {url: `/car`, method: 'DELETE',
      headers: {'Content-Type': 'application/json', },
      data: deleteCarRequest
    },
      options);
    }
  


export const getCarControllerDeleteCarMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof carControllerDeleteCar>>, TError,{data: DeleteCarRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof carControllerDeleteCar>>, TError,{data: DeleteCarRequest}, TContext> => {

const mutationKey = ['carControllerDeleteCar'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof carControllerDeleteCar>>, {data: DeleteCarRequest}> = (props) => {
          const {data} = props ?? {};

          return  carControllerDeleteCar(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CarControllerDeleteCarMutationResult = NonNullable<Awaited<ReturnType<typeof carControllerDeleteCar>>>
    export type CarControllerDeleteCarMutationBody = DeleteCarRequest
    export type CarControllerDeleteCarMutationError = unknown

    export const useCarControllerDeleteCar = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof carControllerDeleteCar>>, TError,{data: DeleteCarRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof carControllerDeleteCar>>,
        TError,
        {data: DeleteCarRequest},
        TContext
      > => {

      const mutationOptions = getCarControllerDeleteCarMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    export const carControllerUpdateCar = (
    updateCarRequest: UpdateCarRequest,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<UpdateCarResponse>(
      {url: `/car`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateCarRequest
    },
      options);
    }
  


export const getCarControllerUpdateCarMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof carControllerUpdateCar>>, TError,{data: UpdateCarRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof carControllerUpdateCar>>, TError,{data: UpdateCarRequest}, TContext> => {

const mutationKey = ['carControllerUpdateCar'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof carControllerUpdateCar>>, {data: UpdateCarRequest}> = (props) => {
          const {data} = props ?? {};

          return  carControllerUpdateCar(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CarControllerUpdateCarMutationResult = NonNullable<Awaited<ReturnType<typeof carControllerUpdateCar>>>
    export type CarControllerUpdateCarMutationBody = UpdateCarRequest
    export type CarControllerUpdateCarMutationError = unknown

    export const useCarControllerUpdateCar = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof carControllerUpdateCar>>, TError,{data: UpdateCarRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof carControllerUpdateCar>>,
        TError,
        {data: UpdateCarRequest},
        TContext
      > => {

      const mutationOptions = getCarControllerUpdateCarMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    export const carControllerChangeMainCar = (
    changeMainCarRequest: ChangeMainCarRequest,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<ChangeMainCarResponse>(
      {url: `/car/main`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: changeMainCarRequest
    },
      options);
    }
  


export const getCarControllerChangeMainCarMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof carControllerChangeMainCar>>, TError,{data: ChangeMainCarRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof carControllerChangeMainCar>>, TError,{data: ChangeMainCarRequest}, TContext> => {

const mutationKey = ['carControllerChangeMainCar'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof carControllerChangeMainCar>>, {data: ChangeMainCarRequest}> = (props) => {
          const {data} = props ?? {};

          return  carControllerChangeMainCar(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CarControllerChangeMainCarMutationResult = NonNullable<Awaited<ReturnType<typeof carControllerChangeMainCar>>>
    export type CarControllerChangeMainCarMutationBody = ChangeMainCarRequest
    export type CarControllerChangeMainCarMutationError = unknown

    export const useCarControllerChangeMainCar = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof carControllerChangeMainCar>>, TError,{data: ChangeMainCarRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof carControllerChangeMainCar>>,
        TError,
        {data: ChangeMainCarRequest},
        TContext
      > => {

      const mutationOptions = getCarControllerChangeMainCarMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    export const carControllerGetCarVendors = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetCarVendorsResponse>(
      {url: `/car/vendors`, method: 'GET', signal
    },
      options);
    }
  

export const getCarControllerGetCarVendorsQueryKey = () => {
    return [`/car/vendors`] as const;
    }

    
export const getCarControllerGetCarVendorsQueryOptions = <TData = Awaited<ReturnType<typeof carControllerGetCarVendors>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof carControllerGetCarVendors>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCarControllerGetCarVendorsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof carControllerGetCarVendors>>> = ({ signal }) => carControllerGetCarVendors(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof carControllerGetCarVendors>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CarControllerGetCarVendorsQueryResult = NonNullable<Awaited<ReturnType<typeof carControllerGetCarVendors>>>
export type CarControllerGetCarVendorsQueryError = unknown


export function useCarControllerGetCarVendors<TData = Awaited<ReturnType<typeof carControllerGetCarVendors>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof carControllerGetCarVendors>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof carControllerGetCarVendors>>,
          TError,
          Awaited<ReturnType<typeof carControllerGetCarVendors>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCarControllerGetCarVendors<TData = Awaited<ReturnType<typeof carControllerGetCarVendors>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof carControllerGetCarVendors>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof carControllerGetCarVendors>>,
          TError,
          Awaited<ReturnType<typeof carControllerGetCarVendors>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCarControllerGetCarVendors<TData = Awaited<ReturnType<typeof carControllerGetCarVendors>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof carControllerGetCarVendors>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useCarControllerGetCarVendors<TData = Awaited<ReturnType<typeof carControllerGetCarVendors>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof carControllerGetCarVendors>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCarControllerGetCarVendorsQueryOptions(options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const carControllerGetCarModels = (
    vendor: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetCarModelsResponse>(
      {url: `/car/${vendor}/models`, method: 'GET', signal
    },
      options);
    }
  

export const getCarControllerGetCarModelsQueryKey = (vendor?: string,) => {
    return [`/car/${vendor}/models`] as const;
    }

    
export const getCarControllerGetCarModelsQueryOptions = <TData = Awaited<ReturnType<typeof carControllerGetCarModels>>, TError = unknown>(vendor: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof carControllerGetCarModels>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCarControllerGetCarModelsQueryKey(vendor);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof carControllerGetCarModels>>> = ({ signal }) => carControllerGetCarModels(vendor, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(vendor), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof carControllerGetCarModels>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CarControllerGetCarModelsQueryResult = NonNullable<Awaited<ReturnType<typeof carControllerGetCarModels>>>
export type CarControllerGetCarModelsQueryError = unknown


export function useCarControllerGetCarModels<TData = Awaited<ReturnType<typeof carControllerGetCarModels>>, TError = unknown>(
 vendor: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof carControllerGetCarModels>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof carControllerGetCarModels>>,
          TError,
          Awaited<ReturnType<typeof carControllerGetCarModels>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCarControllerGetCarModels<TData = Awaited<ReturnType<typeof carControllerGetCarModels>>, TError = unknown>(
 vendor: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof carControllerGetCarModels>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof carControllerGetCarModels>>,
          TError,
          Awaited<ReturnType<typeof carControllerGetCarModels>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCarControllerGetCarModels<TData = Awaited<ReturnType<typeof carControllerGetCarModels>>, TError = unknown>(
 vendor: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof carControllerGetCarModels>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useCarControllerGetCarModels<TData = Awaited<ReturnType<typeof carControllerGetCarModels>>, TError = unknown>(
 vendor: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof carControllerGetCarModels>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCarControllerGetCarModelsQueryOptions(vendor,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



