/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Allta API
 * Allta의 REST API 문서입니다.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateCouponInfoRequest,
  CreateCouponInfoResponse,
  CreateOneCouponRequest,
  CreateOneCouponResponse
} from '.././models';

import { customInstance } from '../../libs/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const couponControllerGetCouponList = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<null>(
      {url: `/coupon`, method: 'GET', signal
    },
      options);
    }
  

export const getCouponControllerGetCouponListQueryKey = () => {
    return [`/coupon`] as const;
    }

    
export const getCouponControllerGetCouponListQueryOptions = <TData = Awaited<ReturnType<typeof couponControllerGetCouponList>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof couponControllerGetCouponList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCouponControllerGetCouponListQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof couponControllerGetCouponList>>> = ({ signal }) => couponControllerGetCouponList(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof couponControllerGetCouponList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CouponControllerGetCouponListQueryResult = NonNullable<Awaited<ReturnType<typeof couponControllerGetCouponList>>>
export type CouponControllerGetCouponListQueryError = unknown


export function useCouponControllerGetCouponList<TData = Awaited<ReturnType<typeof couponControllerGetCouponList>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof couponControllerGetCouponList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof couponControllerGetCouponList>>,
          TError,
          Awaited<ReturnType<typeof couponControllerGetCouponList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCouponControllerGetCouponList<TData = Awaited<ReturnType<typeof couponControllerGetCouponList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof couponControllerGetCouponList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof couponControllerGetCouponList>>,
          TError,
          Awaited<ReturnType<typeof couponControllerGetCouponList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCouponControllerGetCouponList<TData = Awaited<ReturnType<typeof couponControllerGetCouponList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof couponControllerGetCouponList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useCouponControllerGetCouponList<TData = Awaited<ReturnType<typeof couponControllerGetCouponList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof couponControllerGetCouponList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCouponControllerGetCouponListQueryOptions(options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const couponControllerCreateOneCoupon = (
    createOneCouponRequest: CreateOneCouponRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<CreateOneCouponResponse>(
      {url: `/coupon`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createOneCouponRequest, signal
    },
      options);
    }
  


export const getCouponControllerCreateOneCouponMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof couponControllerCreateOneCoupon>>, TError,{data: CreateOneCouponRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof couponControllerCreateOneCoupon>>, TError,{data: CreateOneCouponRequest}, TContext> => {

const mutationKey = ['couponControllerCreateOneCoupon'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof couponControllerCreateOneCoupon>>, {data: CreateOneCouponRequest}> = (props) => {
          const {data} = props ?? {};

          return  couponControllerCreateOneCoupon(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CouponControllerCreateOneCouponMutationResult = NonNullable<Awaited<ReturnType<typeof couponControllerCreateOneCoupon>>>
    export type CouponControllerCreateOneCouponMutationBody = CreateOneCouponRequest
    export type CouponControllerCreateOneCouponMutationError = unknown

    export const useCouponControllerCreateOneCoupon = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof couponControllerCreateOneCoupon>>, TError,{data: CreateOneCouponRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof couponControllerCreateOneCoupon>>,
        TError,
        {data: CreateOneCouponRequest},
        TContext
      > => {

      const mutationOptions = getCouponControllerCreateOneCouponMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    export const couponControllerCreateCouponInfo = (
    createCouponInfoRequest: CreateCouponInfoRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<CreateCouponInfoResponse>(
      {url: `/coupon/coupon-info`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createCouponInfoRequest, signal
    },
      options);
    }
  


export const getCouponControllerCreateCouponInfoMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof couponControllerCreateCouponInfo>>, TError,{data: CreateCouponInfoRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof couponControllerCreateCouponInfo>>, TError,{data: CreateCouponInfoRequest}, TContext> => {

const mutationKey = ['couponControllerCreateCouponInfo'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof couponControllerCreateCouponInfo>>, {data: CreateCouponInfoRequest}> = (props) => {
          const {data} = props ?? {};

          return  couponControllerCreateCouponInfo(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CouponControllerCreateCouponInfoMutationResult = NonNullable<Awaited<ReturnType<typeof couponControllerCreateCouponInfo>>>
    export type CouponControllerCreateCouponInfoMutationBody = CreateCouponInfoRequest
    export type CouponControllerCreateCouponInfoMutationError = unknown

    export const useCouponControllerCreateCouponInfo = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof couponControllerCreateCouponInfo>>, TError,{data: CreateCouponInfoRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof couponControllerCreateCouponInfo>>,
        TError,
        {data: CreateCouponInfoRequest},
        TContext
      > => {

      const mutationOptions = getCouponControllerCreateCouponInfoMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    