/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Allta API
 * Allta의 REST API 문서입니다.
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetCarModelsResponse,
  GetCarVendorsResponse
} from '.././models';

import { customInstance } from '../../libs/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const carModelControllerGetCarVendors = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetCarVendorsResponse>(
      {url: `/car-model/vendors`, method: 'GET', signal
    },
      options);
    }
  

export const getCarModelControllerGetCarVendorsQueryKey = () => {
    return [`/car-model/vendors`] as const;
    }

    
export const getCarModelControllerGetCarVendorsQueryOptions = <TData = Awaited<ReturnType<typeof carModelControllerGetCarVendors>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof carModelControllerGetCarVendors>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCarModelControllerGetCarVendorsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof carModelControllerGetCarVendors>>> = ({ signal }) => carModelControllerGetCarVendors(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof carModelControllerGetCarVendors>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CarModelControllerGetCarVendorsQueryResult = NonNullable<Awaited<ReturnType<typeof carModelControllerGetCarVendors>>>
export type CarModelControllerGetCarVendorsQueryError = unknown


export function useCarModelControllerGetCarVendors<TData = Awaited<ReturnType<typeof carModelControllerGetCarVendors>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof carModelControllerGetCarVendors>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof carModelControllerGetCarVendors>>,
          TError,
          Awaited<ReturnType<typeof carModelControllerGetCarVendors>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCarModelControllerGetCarVendors<TData = Awaited<ReturnType<typeof carModelControllerGetCarVendors>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof carModelControllerGetCarVendors>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof carModelControllerGetCarVendors>>,
          TError,
          Awaited<ReturnType<typeof carModelControllerGetCarVendors>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCarModelControllerGetCarVendors<TData = Awaited<ReturnType<typeof carModelControllerGetCarVendors>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof carModelControllerGetCarVendors>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useCarModelControllerGetCarVendors<TData = Awaited<ReturnType<typeof carModelControllerGetCarVendors>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof carModelControllerGetCarVendors>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCarModelControllerGetCarVendorsQueryOptions(options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const carModelControllerGetCarModels = (
    vendor: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetCarModelsResponse>(
      {url: `/car-model/models/${vendor}`, method: 'GET', signal
    },
      options);
    }
  

export const getCarModelControllerGetCarModelsQueryKey = (vendor?: string,) => {
    return [`/car-model/models/${vendor}`] as const;
    }

    
export const getCarModelControllerGetCarModelsQueryOptions = <TData = Awaited<ReturnType<typeof carModelControllerGetCarModels>>, TError = unknown>(vendor: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof carModelControllerGetCarModels>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCarModelControllerGetCarModelsQueryKey(vendor);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof carModelControllerGetCarModels>>> = ({ signal }) => carModelControllerGetCarModels(vendor, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(vendor), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof carModelControllerGetCarModels>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CarModelControllerGetCarModelsQueryResult = NonNullable<Awaited<ReturnType<typeof carModelControllerGetCarModels>>>
export type CarModelControllerGetCarModelsQueryError = unknown


export function useCarModelControllerGetCarModels<TData = Awaited<ReturnType<typeof carModelControllerGetCarModels>>, TError = unknown>(
 vendor: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof carModelControllerGetCarModels>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof carModelControllerGetCarModels>>,
          TError,
          Awaited<ReturnType<typeof carModelControllerGetCarModels>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCarModelControllerGetCarModels<TData = Awaited<ReturnType<typeof carModelControllerGetCarModels>>, TError = unknown>(
 vendor: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof carModelControllerGetCarModels>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof carModelControllerGetCarModels>>,
          TError,
          Awaited<ReturnType<typeof carModelControllerGetCarModels>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCarModelControllerGetCarModels<TData = Awaited<ReturnType<typeof carModelControllerGetCarModels>>, TError = unknown>(
 vendor: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof carModelControllerGetCarModels>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useCarModelControllerGetCarModels<TData = Awaited<ReturnType<typeof carModelControllerGetCarModels>>, TError = unknown>(
 vendor: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof carModelControllerGetCarModels>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCarModelControllerGetCarModelsQueryOptions(vendor,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



