/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Allta API
 * Allta의 REST API 문서입니다.
 * OpenAPI spec version: 1.0
 */

export interface Address {
  /** ID */
  id: string;
  /** 별명 */
  nickname: string;
  /** 위도 */
  lat: number;
  /** 전체 주소 */
  fullAddress: string;
  /** 경도 */
  lng: number;
}
