/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta API
 * Allta API 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */

export interface BannerListItem {
  /** ID */
  id: string;
  /** 배너 종류 */
  type: string;
  /** 순서 */
  index: number;
  /** 이미지 */
  image: string;
  /**
   * URL
   * @nullable
   */
  url?: string | null;
}
