/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Allta API
 * Allta의 REST API 문서입니다.
 * OpenAPI spec version: 1.0
 */

export interface Car {
  /** ID */
  id: string;
  /** 제조사 */
  carBrand: string;
  /** 모델명 */
  carModel: string;
  /** 차량 종류 */
  carType: string;
  /** 차량 번호 */
  carNumber: string;
  /** 대표 차량 여부 */
  isMain: boolean;
}
