/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Allta API
 * Allta API 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */

export interface Card {
  /** ID */
  id: string;
  /** 조회용 카드 번호 */
  cardDisplayNumber: string;
  /** 카드사 */
  cardCompany: string;
  /** 대표 카드 여부 */
  isMain: boolean;
}
