/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Allta API
 * Allta의 REST API 문서입니다.
 * OpenAPI spec version: 1.0
 */
import type { CarModelType } from './carModelType';
import type { CarModelName } from './carModelName';

export interface CarModel {
  /** 차종 */
  type?: CarModelType;
  /** 모델명 */
  name?: CarModelName;
}
