/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Allta API
 * Allta API 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */

export interface CheckUserBySocialIdRequest {
  /** 로그인 종류 */
  loginKind: string;
  /** 소셜 로그인 ID */
  socialId: string;
}
