/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta API
 * Allta API 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */

export interface CheckIsRejoinResponse {
  /** 결과 여부 */
  ok: boolean;
  /** 재가입 여부 */
  isRejoin: boolean;
}
