/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta API
 * Allta API 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */

export type CouponControllerGetAvailableCouponListParams = {
/**
 * 이용권 종류
 * @nullable
 */
passType?: string | null;
/**
 * 서비스 종류
 * @nullable
 */
serviceType?: string | null;
/**
 * 매장 ID
 */
storeId: string;
};
