/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Allta API
 * Allta의 REST API 문서입니다.
 * OpenAPI spec version: 1.0
 */
import type { CouponListItemExpiredAt } from './couponListItemExpiredAt';

export interface CouponListItem {
  /** ID */
  id: string;
  /** 쿠폰 이름 */
  name: string;
  /** 쿠폰 종류 */
  type: string;
  /**
   * 이용권 종류
   * @nullable
   */
  passType?: string | null;
  /**
   * 서비스 종류
   * @nullable
   */
  serviceType?: string | null;
  /** 할인 종류 */
  discountType: string;
  /** 할인 금액 */
  discountValue: number;
  /** 만료일 */
  expiredAt: CouponListItemExpiredAt;
  /**
   * 적용 매장 수
   * @nullable
   */
  targetStoreCount: number | null;
}
