/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta API
 * Allta API 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */

export interface CreateUserResult {
  /** 회원 ID */
  userId: string;
  /** 재가입 여부 */
  isRejoined: boolean;
  /** 신규회원 쿠폰 발행 여부 */
  isCouponReceived: boolean;
}
