/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Allta API
 * Allta의 REST API 문서입니다.
 * OpenAPI spec version: 1.0
 */

/**
 * 차량 제조사
 * @nullable
 */
export type CreateUserDtoCarBrand = { [key: string]: unknown } | null;
