/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Allta API
 * Allta의 REST API 문서입니다.
 * OpenAPI spec version: 1.0
 */

export interface CreateUserRequest {
  /** 이름 */
  name: string;
  /** 이메일 */
  email: string;
  /** 로그인 종류 */
  loginKind: string;
  /** 소셜 로그인 ID */
  socialId: string;
  /** 전화번호 */
  phoneNumber: string;
}
