/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Allta API
 * Allta의 REST API 문서입니다.
 * OpenAPI spec version: 1.0
 */
import type { CreateUserDtoLoginKind } from './createUserDtoLoginKind';
import type { CreateUserDtoJoinPath } from './createUserDtoJoinPath';
import type { CreateUserDtoCarBrand } from './createUserDtoCarBrand';
import type { CreateUserDtoCarModel } from './createUserDtoCarModel';
import type { CreateUserDtoCarType } from './createUserDtoCarType';
import type { CreateUserDtoCarNumber } from './createUserDtoCarNumber';

export interface CreateUserDto {
  /** 이름 */
  name: string;
  /** 이메일 */
  email: string;
  /** 로그인 종류 */
  loginKind: CreateUserDtoLoginKind;
  /** 소셜 로그인 ID */
  socialId: string;
  /** 전화번호 */
  phoneNumber: string;
  /** 가입 경로 */
  joinPath?: CreateUserDtoJoinPath;
  /** 차량 제조사 */
  carBrand?: CreateUserDtoCarBrand;
  /** 차량 모델명 */
  carModel?: CreateUserDtoCarModel;
  /** 차량 종류 */
  carType?: CreateUserDtoCarType;
  /** 차량 번호 */
  carNumber?: CreateUserDtoCarNumber;
}
