/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Allta API
 * Allta API 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */

export interface CreateOneCouponRequest {
  /** 쿠폰 정보 ID */
  couponInfoId: string;
  /** 회원 ID */
  userId: string;
}
