/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Allta API
 * Allta의 REST API 문서입니다.
 * OpenAPI spec version: 1.0
 */

/**
 * 차량 종류
 */
export type CreateUserDtoCarType = typeof CreateUserDtoCarType[keyof typeof CreateUserDtoCarType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateUserDtoCarType = {
  SEDAN: 'SEDAN',
  SUV: 'SUV',
  VAN: 'VAN',
} as const;
