/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Allta API
 * Allta의 REST API 문서입니다.
 * OpenAPI spec version: 1.0
 */

/**
 * 쿠폰 등록 종료일
 */
export type CreateCouponInfoRequestEndDate = string | null;
