/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Allta API
 * Allta의 REST API 문서입니다.
 * OpenAPI spec version: 1.0
 */

/**
 * 로그인 종류
 */
export type CreateUserDtoLoginKind = typeof CreateUserDtoLoginKind[keyof typeof CreateUserDtoLoginKind];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateUserDtoLoginKind = {
  KAKAO: 'KAKAO',
  GOOGLE: 'GOOGLE',
  APPLE: 'APPLE',
} as const;
