/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta API
 * Allta API 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */

export interface EventListItem {
  /** ID */
  id: string;
  /** 썸네일 */
  thumbnail: string;
  /** 이벤트 이름 */
  title: string;
  /**
   * 이벤트 시작일
   * @nullable
   */
  startDate?: string | null;
  /**
   * 이벤트 종료일
   * @nullable
   */
  endDate?: string | null;
}
