/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta API
 * Allta API 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */

/**
 * 일회권(핸즈클리닝)
 */
export type GetAvailablePassesResponseHandsTicket = { [key: string]: unknown };
