/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta API
 * Allta API 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */

/**
 * 프리미엄 구독권(자동세차)
 */
export type GetAvailablePassesResponseAutoPremium = { [key: string]: unknown };
