/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Allta API
 * Allta의 REST API 문서입니다.
 * OpenAPI spec version: 1.0
 */
import type { Address } from './address';
import type { PaginationMetaEntity } from './paginationMetaEntity';

export interface GetAddressesResponse {
  /** 결과 여부 */
  ok: boolean;
  /** 주소 목록 */
  data: Address[];
  /** 메타 정보 */
  meta: PaginationMetaEntity;
}
