/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta API
 * Allta API 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */
import type { GetAvailablePassesResponseAutoTicket } from './getAvailablePassesResponseAutoTicket';
import type { GetAvailablePassesResponseHandsTicket } from './getAvailablePassesResponseHandsTicket';
import type { GetAvailablePassesResponseAutoStandard } from './getAvailablePassesResponseAutoStandard';
import type { GetAvailablePassesResponseHandsStandard } from './getAvailablePassesResponseHandsStandard';
import type { GetAvailablePassesResponseAutoPremium } from './getAvailablePassesResponseAutoPremium';
import type { GetAvailablePassesResponseHandsPremium } from './getAvailablePassesResponseHandsPremium';

export interface GetAvailablePassesResponse {
  /** 결과 여부 */
  ok: boolean;
  /** 이용권 보유 여부 */
  hasAvailablePass: boolean;
  /** 일회권(자동세차) */
  autoTicket: GetAvailablePassesResponseAutoTicket;
  /** 일회권(핸즈클리닝) */
  handsTicket: GetAvailablePassesResponseHandsTicket;
  /** 스탠다드 구독권(자동세차) */
  autoStandard: GetAvailablePassesResponseAutoStandard;
  /** 스탠다드 구독권(핸즈클리닝) */
  handsStandard: GetAvailablePassesResponseHandsStandard;
  /** 프리미엄 구독권(자동세차) */
  autoPremium: GetAvailablePassesResponseAutoPremium;
  /** 프리미엄 구독권(핸즈클리닝) */
  handsPremium: GetAvailablePassesResponseHandsPremium;
}
