/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Allta API
 * Allta API 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */
import type { CouponListItem } from './couponListItem';

export interface GetCouponListResponse {
  /** 결과 여부 */
  ok: boolean;
  /** 쿠폰 목록 */
  data: CouponListItem[];
}
