/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Allta API
 * Allta API 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */
import type { Card } from './card';

export interface GetCardListResponse {
  /** 결과 여부 */
  ok: boolean;
  /** 차량 목록 */
  data: Card[];
}
