/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta API
 * Allta API 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */
import type { EventListItem } from './eventListItem';

export interface GetEventListResponse {
  /** 결과 여부 */
  ok: boolean;
  /** 이벤트 목록 */
  data: EventListItem[];
}
