/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta API
 * Allta API 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */
import type { InquiryListItem } from './inquiryListItem';
import type { PaginationMetaEntity } from './paginationMetaEntity';

export interface GetInquiryListResponse {
  /** 결과 여부 */
  ok: boolean;
  /** 문의내역 목록 */
  data: InquiryListItem[];
  /** 메타 정보 */
  meta: PaginationMetaEntity;
}
