/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Allta API
 * Allta API 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */

export interface GetMarketingAgreementStatusResponse {
  /** 결과 여부 */
  ok: boolean;
  /** 마케팅 활용 동의 여부 */
  isMarketing: boolean;
}
