/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta API
 * Allta API 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */
import type { Notification } from './notification';
import type { PaginationMetaEntity } from './paginationMetaEntity';

export interface GetNotificationsResponse {
  /** 결과 여부 */
  ok: boolean;
  /** 알림 목록 */
  data: Notification[];
  /** 메타 정보 */
  meta: PaginationMetaEntity;
}
