/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta API
 * Allta API 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */
import type { PaymentItem } from './paymentItem';
import type { PaginationMetaEntity } from './paginationMetaEntity';

export interface GetPaymentListResponse {
  /** 결과 여부 */
  ok: boolean;
  /** 결제 내역 스냅샷 목록 */
  data: PaymentItem[];
  /** 메타 정보 */
  meta: PaginationMetaEntity;
}
