/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Allta API
 * Allta API 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */
import type { PurchaseItem } from './purchaseItem';
import type { PaginationMetaEntity } from './paginationMetaEntity';

export interface GetPurchaseListResponse {
  /** 결과 여부 */
  ok: boolean;
  /** 결제 내역 목록 */
  data: PurchaseItem[];
  /** 메타 정보 */
  meta: PaginationMetaEntity;
}
