/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Allta API
 * Allta의 REST API 문서입니다.
 * OpenAPI spec version: 1.0
 */
import type { GetStoreDetailResponseStore } from './getStoreDetailResponseStore';

export interface GetStoreDetailResponse {
  /** 결과 여부 */
  ok: boolean;
  /**
   * 매장 상세 정보
   * @nullable
   */
  store: GetStoreDetailResponseStore;
}
