/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta API
 * Allta API 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */
import type { SubscriptionItem } from './subscriptionItem';

export interface GetSubscriptionListReponse {
  /** 결과 여부 */
  ok: boolean;
  /** 구독권 */
  data: SubscriptionItem[];
}
