/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Allta API
 * Allta의 REST API 문서입니다.
 * OpenAPI spec version: 1.0
 */
import type { StoreDetailItem } from './storeDetailItem';

/**
 * 매장 상세 정보
 * @nullable
 */
export type GetStoreDetailResponseStore = StoreDetailItem | null;
