/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Allta API
 * Allta API 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */
import type { SubscriptionDetailItem } from './subscriptionDetailItem';

export interface GetSubscriptionDetailResponse {
  /** 결과 여부 */
  ok: boolean;
  /** 구독권 상세 정보 */
  data: SubscriptionDetailItem;
}
