/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Allta API
 * Allta의 REST API 문서입니다.
 * OpenAPI spec version: 1.0
 */
import type { StoreListItem } from './storeListItem';
import type { PaginationMetaEntity } from './paginationMetaEntity';

export interface GetStoreListResponse {
  /** 결과 여부 */
  ok: boolean;
  /** 매장 목록 */
  data: StoreListItem[];
  /** 메타 정보 */
  meta: PaginationMetaEntity;
}
