/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Allta API
 * Allta API 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */
import type { TicketDetailItem } from './ticketDetailItem';

export interface GetTicketDetailResponse {
  /** 결과 여부 */
  ok: boolean;
  /** 일회권 상세 정보 */
  data: TicketDetailItem;
}
