/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Allta API
 * Allta API 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */
import type { TicketItem } from './ticketItem';
import type { PaginationMetaEntity } from './paginationMetaEntity';

export interface GetTicketListReponse {
  /** 결과 여부 */
  ok: boolean;
  /** 일회권 */
  data: TicketItem[];
  /** 메타 정보 */
  meta: PaginationMetaEntity;
}
