/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Allta API
 * Allta의 REST API 문서입니다.
 * OpenAPI spec version: 1.0
 */

export interface GetUserProfileResponse {
  /** 이름 */
  name: string;
  /** 보유 일회권 개수 */
  totalTickets: number;
  /** 보유 스탠다드 구독권 개수 */
  totalStandards: number;
  /** 보유 프리미엄 구독권 개수 */
  totalPremiums: number;
}
