/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta API
 * Allta API 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */

export interface InquiryListItem {
  /** ID */
  id: string;
  /** 내용 */
  content: string;
  /** 문의일 */
  createdAt: string;
  /**
   * 답변일
   * @nullable
   */
  answeredAt?: string | null;
  /** 답변 여부 */
  isAnswered: boolean;
}
