/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Allta API
 * Allta의 REST API 문서입니다.
 * OpenAPI spec version: 1.0
 */
import type { LoginBySocialIdDtoLoginKind } from './loginBySocialIdDtoLoginKind';

export interface LoginBySocialIdDto {
  /** 로그인 종류 */
  loginKind: LoginBySocialIdDtoLoginKind;
  /** 소셜 로그인 ID */
  socialId: string;
}
