/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Allta API
 * Allta의 REST API 문서입니다.
 * OpenAPI spec version: 1.0
 */

export interface LoginBySocialIdResponse {
  /** 로그인 성공 여부 */
  ok: boolean;
}
