/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta API
 * Allta API 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */

export interface MyStoreListItem {
  /** ID */
  id: string;
  /** 이름 */
  name: string;
  /** 주소 */
  address: string;
  /** 위도 */
  lat: number;
  /** 경도 */
  lng: number;
  /**
   * 대표 이미지
   * @nullable
   */
  mainImage?: string | null;
  /**
   * 이용권 가격
   * @nullable
   */
  passPrice?: string | null;
  /**
   * 영업 시간
   * @nullable
   */
  businessHours?: string | null;
  /**
   * 휴게 시간
   * @nullable
   */
  breakTime?: string | null;
  /**
   * 휴무일
   * @nullable
   */
  holidays?: string | null;
  /**
   * 직영 ID
   * @nullable
   */
  storeGroupId?: string | null;
  /** 보유 이용권 종류 */
  passTypes: string;
}
