/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta API
 * Allta API 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */

export interface Notification {
  /** ID */
  id: string;
  /**
   * 태그
   * @nullable
   */
  tag?: string | null;
  /** 이름 */
  title: string;
  /** 내용 */
  content: string;
  /**
   * URL
   * @nullable
   */
  url?: string | null;
  /** 생성일 */
  createdAt: string;
  /** 조회 여부 */
  isRead: boolean;
}
