/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Allta API
 * Allta의 REST API 문서입니다.
 * OpenAPI spec version: 1.0
 */
import type { NotificationTag } from './notificationTag';
import type { NotificationUrl } from './notificationUrl';

export interface Notification {
  /** ID */
  id: string;
  /** 태그 */
  tag?: NotificationTag;
  /** 이름 */
  title: string;
  /** 내용 */
  content: string;
  /** URL */
  url?: NotificationUrl;
  /** 생성일 */
  createdAt: string;
  /** 조회 여부 */
  isRead: boolean;
}
