/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Allta API
 * Allta의 REST API 문서입니다.
 * OpenAPI spec version: 1.0
 */

export interface PaginationMetaEntity {
  /** 전체 데이터 수 */
  totalCount: number;
  /** 마지막 페이지 여부 */
  hasNextPage: boolean;
}
