/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta API
 * Allta API 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */

export interface PurchaseItem {
  /** ID */
  id: string;
  /** 결제 상태 */
  status: string;
  /** 상품 종류 */
  productType: string;
  /** 서비스 종류 */
  serviceType: string;
  /** 매장 이름 */
  storeName: string;
  /** 최종 결제 금액 */
  totalAmount: number;
  /**
   * 차량 번호
   * @nullable
   */
  carNumber?: string | null;
  /** 생성일 */
  createdAt: string;
}
