/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Allta API
 * Allta API 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */
import type { PurchaseDetailPaymentItem } from './purchaseDetailPaymentItem';

export interface PurchaseDetailItem {
  /** 결제 상태 */
  status: string;
  /** 상품 종류 */
  productType: string;
  /** 서비스 종류 */
  serviceType: string;
  /** 매장 이름 */
  storeName: string;
  /** 할인 전 금액 */
  originalAmount: number;
  /** 할인 금액 */
  discountAmount: number;
  /** 최종 결제 금액 */
  totalAmount: number;
  /**
   * 차량 번호
   * @nullable
   */
  carNumber?: string | null;
  /** 카드 번호 마지막 4자리 */
  cardDisplayNumber: string;
  /** 생성일 */
  createdAt: string;
  /** 결제 내역 스냅샷 목록 */
  payments: PurchaseDetailPaymentItem[];
}
