/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Allta API
 * Allta API 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */
import type { PurchaseDetail } from './purchaseDetail';

export interface PurchasePassResponse {
  /** 결과 여부 */
  ok: boolean;
  /** 결제 내역 */
  data: PurchaseDetail;
}
