/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Allta API
 * Allta API 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */

export interface PurchaseDetailPaymentItem {
  /** 결제 상태 */
  status: string;
  /** 변동 금액 */
  amount: number;
  /** 생성일 */
  createdAt: string;
}
