/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta API
 * Allta API 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */

export interface PurchaseResult {
  /** 매장 ID */
  storeId: string;
  /** 매장 이름 */
  storeName: string;
  /** 서비스 종류 */
  serviceType: string;
  /** 이용권 종류 */
  productType: string;
  /** 차량 번호 */
  carNumber: string;
  /** 결제 일시 */
  approvedAt: string;
  /** 결제 금액 */
  totalAmount: number;
}
