/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Allta API
 * Allta API 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */

export interface PurchasePassRequest {
  /** 상품 종류 */
  productType: string;
  /** 서비스 종류 */
  serviceType: string;
  /**
   * 쿠폰 ID
   * @nullable
   */
  couponId?: string | null;
  /** 제조사 */
  carBrand: string;
  /** 차종 */
  carType: string;
  /** 모델명 */
  carModel: string;
  /** 차량 번호 */
  carNumber: string;
  /** 매장 ID */
  storeId: string;
  /** 카드 ID */
  cardId: string;
}
