/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta API
 * Allta API 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */

export interface ReceiptCouponData {
  /** 할인 종류 */
  discountType: string;
  /** 할인 금액 */
  discountValue: number;
  /** 생성일 */
  createdAt: string;
  /** 만료일 */
  expiredAt: string;
  /** 매장 이름 */
  storeName: string;
}
