/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Allta API
 * Allta API 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */
import type { RegisterStoreRequestReceiptDiscountOneOf } from './registerStoreRequestReceiptDiscountOneOf';

/**
 * 주유 할인 가격
 */
export type RegisterStoreRequestReceiptDiscount = RegisterStoreRequestReceiptDiscountOneOf | unknown;
