/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta API
 * Allta API 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */
import type { RegisterStoreRequestPassPrice } from './registerStoreRequestPassPrice';
import type { RegisterStoreRequestReceiptDiscount } from './registerStoreRequestReceiptDiscount';
import type { RegisterStoreRequestBusinessHours } from './registerStoreRequestBusinessHours';

export interface RegisterStoreRequest {
  /** 이름 */
  name: string;
  /** 전화번호 */
  phoneNumber: string;
  /** 주소 */
  address: string;
  /** 위도 */
  lat: number;
  /** 경도 */
  lng: number;
  /** 매장 종류 */
  storeType: string;
  /**
   * 대표 이미지
   * @nullable
   */
  mainImage?: string | null;
  /**
   * 매장 소개
   * @nullable
   */
  description?: string | null;
  /**
   * 유의사항
   * @nullable
   */
  policy?: string | null;
  /**
   * 휴게 시간
   * @nullable
   */
  breakTime?: string | null;
  /** 대표 이름 */
  ceoName: string;
  /** 대표 전화번호 */
  ceoPhoneNumber: string;
  /**
   * 직영 ID
   * @nullable
   */
  storeGroupId?: string | null;
  /** 이용권 가격 */
  passPrice?: RegisterStoreRequestPassPrice;
  /** 주유 할인 가격 */
  receiptDiscount?: RegisterStoreRequestReceiptDiscount;
  /** 영업 시간 */
  businessHours?: RegisterStoreRequestBusinessHours;
}
