/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Allta API
 * Allta의 REST API 문서입니다.
 * OpenAPI spec version: 1.0
 */

export interface RegisterCarRequest {
  /** 제조사 */
  carVendor: string;
  /** 차종 */
  carType: string;
  /** 모델명 */
  carModel: string;
  /** 차량 번호 */
  carNumber: string;
}
