/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta API
 * Allta API 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */

export interface RegisterExtraInfoRequest {
  /** 제조사 */
  carVendor?: string;
  /** 차종 */
  carType?: string;
  /** 모델명 */
  carModel?: string;
  /** 차량 번호 */
  carNumber?: string;
  /** 카드 번호 */
  cardNumber?: string;
  /** 카드 비밀번호 (앞 두자리) */
  cardPassword?: string;
  /** 유효기간 (년) */
  expirationYear?: string;
  /** 유효기간 (월) */
  expirationMonth?: string;
  /** 생년월일 또는 사업자등록번호 */
  identityNumber?: string;
}
