/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Allta API
 * Allta의 REST API 문서입니다.
 * OpenAPI spec version: 1.0
 */
import type { RegisterAddresssRequestBuildingName } from './registerAddresssRequestBuildingName';
import type { RegisterAddresssRequestRoadName } from './registerAddresssRequestRoadName';

export interface RegisterAddresssRequest {
  /** 별명 */
  nickname: string;
  /** 위도 */
  lat: number;
  /** 전체 주소 */
  fullAddress: string;
  /** 건물명 */
  buildingName?: RegisterAddresssRequestBuildingName;
  /** 주소(시, 도 단위) */
  region1DepthName: string;
  /** 주소(구 단위) */
  region2DepthName: string;
  /** 주소(동 단위) */
  region3DepthName: string;
  /** 도로명 */
  roadName?: RegisterAddresssRequestRoadName;
  /** 경도 */
  lng: number;
}
