/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta API
 * Allta API 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */

export interface RegisterAddresssRequest {
  /** 별명 */
  nickname: string;
  /** 위도 */
  lat: number;
  /** 경도 */
  lng: number;
  /** 전체 주소 */
  fullAddress: string;
  /**
   * 건물명
   * @nullable
   */
  buildingName?: string | null;
  /** 주소(시, 도 단위) */
  region1DepthName: string;
  /** 주소(구 단위) */
  region2DepthName: string;
  /** 주소(동 단위) */
  region3DepthName: string;
  /**
   * 도로명
   * @nullable
   */
  roadName?: string | null;
}
