/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta API
 * Allta API 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */

export interface SignUpFromWebRequest {
  /** 이름 */
  name: string;
  /**
   * 이메일
   * @nullable
   */
  email?: string | null;
  /** 로그인 종류 */
  loginKind: string;
  /** 소셜 로그인 ID */
  socialId: string;
  /** 전화번호 */
  phoneNumber: string;
  /**
   * 이메일
   * @nullable
   */
  sex?: string | null;
  /**
   * 주소
   * @nullable
   */
  address?: string | null;
  /**
   * 법인 코드
   * @nullable
   */
  companyCode?: string | null;
  /**
   * 회원이 등록한 추천인 코드
   * @nullable
   */
  referrerCode?: string | null;
  /** 마케팅 수신 여부 */
  isMarketing: boolean;
  /**
   * 생년월일
   * @nullable
   */
  birthDate?: string | null;
}
