/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Allta API
 * Allta의 REST API 문서입니다.
 * OpenAPI spec version: 1.0
 */

export type StoreControllerGetStoresParams = {
/**
 * 위도
 */
lat?: number;
/**
 * 경도
 */
lng?: number;
/**
 * 서비스 종류
 */
serviceType: string;
/**
 * 이용권 종류
 */
passType?: string;
/**
 * 가져올 데이터 수
 */
take: number;
/**
 * 건너뛸 데이터 수
 */
skip: number;
};
