/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Allta API
 * Allta의 REST API 문서입니다.
 * OpenAPI spec version: 1.0
 */
import type { StoreGroupListItemMainImage } from './storeGroupListItemMainImage';

export interface StoreGroupListItem {
  /** ID */
  id: string;
  /** 이름 */
  name: string;
  /** 주소 */
  address: string;
  /** 위도 */
  lat: number;
  /** 경도 */
  lng: number;
  /** 대표 이미지 */
  mainImage?: StoreGroupListItemMainImage;
}
