/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Allta API
 * Allta의 REST API 문서입니다.
 * OpenAPI spec version: 1.0
 */
import type { StoreMainImage } from './storeMainImage';
import type { StorePassPrice } from './storePassPrice';
import type { StoreBusinessHours } from './storeBusinessHours';
import type { StoreBreakTime } from './storeBreakTime';
import type { StoreStoreGroupId } from './storeStoreGroupId';

export interface Store {
  /** ID */
  id: string;
  /** 이름 */
  name: string;
  /** 주소 */
  address: string;
  /** 위도 */
  lat: number;
  /** 경도 */
  lng: number;
  /** 대표 이미지 */
  mainImage?: StoreMainImage;
  /** 이용권 가격 */
  passPrice?: StorePassPrice;
  /** 영업 시간 */
  businessHours?: StoreBusinessHours;
  /** 휴게 시간 */
  breakTime?: StoreBreakTime;
  /** 법인 ID */
  storeGroupId?: StoreStoreGroupId;
}
