/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Allta API
 * Allta의 REST API 문서입니다.
 * OpenAPI spec version: 1.0
 */
import type { StoreListItemMainImage } from './storeListItemMainImage';
import type { StoreListItemTags } from './storeListItemTags';
import type { StoreListItemPassPrice } from './storeListItemPassPrice';
import type { StoreListItemBusinessHours } from './storeListItemBusinessHours';
import type { StoreListItemBreakTime } from './storeListItemBreakTime';
import type { StoreListItemGroupStoresCount } from './storeListItemGroupStoresCount';

export interface StoreListItem {
  /** ID */
  id: string;
  /** 이름 */
  name: string;
  /** 주소 */
  address: string;
  /** 위도 */
  lat: number;
  /** 경도 */
  lng: number;
  /** 대표 이미지 */
  mainImage?: StoreListItemMainImage;
  /** 태그 */
  tags?: StoreListItemTags;
  /** 이용권 가격 */
  passPrice?: StoreListItemPassPrice;
  /** 영업 시간 */
  businessHours?: StoreListItemBusinessHours;
  /** 휴게 시간 */
  breakTime?: StoreListItemBreakTime;
  /**
   * 직영 ID
   * @nullable
   */
  storeGroupId?: string | null;
  /** 직영 매장 수 */
  groupStoresCount: StoreListItemGroupStoresCount;
}
