/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta API
 * Allta API 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */

export interface StoreTicketListItem {
  /** ID */
  id: string;
  /** 서비스 종류 */
  serviceType: string;
  /** 생성일 */
  createdAt: string;
  /** 만료일 */
  expiredAt: string;
}
