/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Allta API
 * Allta의 REST API 문서입니다.
 * OpenAPI spec version: 1.0
 */
import type { Object } from './object';

export type StoreControllerGetStoreGroupListParams = {
/**
 * 직영 ID
 */
storeGroupId?: Object;
/**
 * 가져올 데이터 수
 */
take: number;
/**
 * 건너뛸 데이터 수
 */
skip: number;
};
