/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Allta API
 * Allta의 REST API 문서입니다.
 * OpenAPI spec version: 1.0
 */

/**
 * 스탠다드 구독권 최대 사용 횟수
 */
export type StoreDetailItemStandardMaxUsage = number | null;
