/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Allta API
 * Allta의 REST API 문서입니다.
 * OpenAPI spec version: 1.0
 */
import type { StoreStoreImage } from './storeStoreImage';
import type { StorePassPrice } from './storePassPrice';
import type { StoreStoreGroupId } from './storeStoreGroupId';

export interface Store {
  /** ID */
  id: string;
  /** 이름 */
  name: string;
  /** 주소 */
  address: string;
  /** 위도 */
  lat: number;
  /** 경도 */
  lng: number;
  /** 매장 이미지 */
  storeImage?: StoreStoreImage;
  /** 이용권 가격 */
  passPrice?: StorePassPrice;
  /** 매장 그룹 ID */
  storeGroupId?: StoreStoreGroupId;
}
