/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Allta API
 * Allta API 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */
import type { SubscriptionStoreItem } from './subscriptionStoreItem';
import type { SubscriptionSnapshotItem } from './subscriptionSnapshotItem';

export interface SubscriptionDetailItem {
  /** ID */
  id: string;
  /** 구독권 종류 */
  type: string;
  /** 일회권 상태 */
  status: string;
  /** 서비스 종류 */
  serviceType: string;
  /** 일회권 금액 */
  amount: number;
  /** 차량 번호 */
  carNumber: string;
  /** 자동결제 날짜 */
  billingDate: number;
  /** 마지막 결제일 */
  payedAt: string;
  /** 매장 정보 */
  store: SubscriptionStoreItem;
  /** 구독권 스냅샷 */
  subscriptionSnapshot: SubscriptionSnapshotItem;
}
