/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Allta API
 * Allta API 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */
import type { TicketStoreItem } from './ticketStoreItem';

export interface TicketDetailItem {
  /** ID */
  id: string;
  /** 일회권 상태 */
  status: string;
  /** 서비스 종류 */
  serviceType: string;
  /** 일회권 금액 */
  amount: number;
  /** 차량 번호 */
  carNumber: string;
  /** 생성일 */
  createdAt: string;
  /** 만료일 */
  expiredAt: string;
  /** 매장 정보 */
  store: TicketStoreItem;
}
