/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Allta API
 * Allta API 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */

export interface UpdateCarRequest {
  /** ID */
  id: string;
  /** 제조사 */
  vendor: string;
  /** 차량 종류 */
  type: string;
  /** 모델명 */
  model: string;
  /** 차량 번호 */
  number: string;
}
