/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta API
 * Allta API 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */

export interface UpdateSubscriptionCardRequest {
  /** 구독권 ID */
  subscriptionId: string;
  /** 카드 ID */
  cardId: string;
}
