/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta API
 * Allta API 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */

export interface UsablePassByCarNumberResult {
  /** 회원명 */
  userName: string;
  /** 차종 */
  carType: string;
  /** 차량번호 */
  carNumber: string;
  /** 이용권 ID */
  passId: string;
  /** 이용권 종류 */
  passType: string;
}
