/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Allta API
 * Allta API 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */

export interface UserRefferalCodeItem {
  /** 추천인 코드 */
  referralCode: string;
  /** 추천인 코드 등록 여부 */
  isReffered: boolean;
}
