/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Allta API
 * Allta API 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */

export interface UserReferralCodeItem {
  /** 추천인 코드 */
  referralCode: string;
  /**
   * 회원이 등록한 추천인 코드
   * @nullable
   */
  referrerCode?: string | null;
}
