/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta API
 * Allta API 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */

export interface UseSubscriptionServiceData {
  /** 서비스 종류 */
  serviceType: string;
  /** 매장 이름 */
  storeName: string;
  /**
   * 제조사
   * @nullable
   */
  carBrand?: string | null;
  /**
   * 차량 종류
   * @nullable
   */
  carType?: string | null;
  /**
   * 모델명
   * @nullable
   */
  carModel?: string | null;
  /**
   * 차량 번호
   * @nullable
   */
  carNumber?: string | null;
  /** 생성일 */
  createdAt: string;
}
