/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta API
 * Allta API 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */

export interface UseSubscriptionRequest {
  /** 구독권 ID */
  subscriptionId: string;
  /** 매장 ID */
  storeId: string;
}
