/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Allta API
 * Allta API 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */

export interface UseTicketServiceData {
  /** 서비스 종류 */
  serviceType: string;
  /** 매장 이름 */
  storeName: string;
  /** 제조사 */
  carBrand: string;
  /** 모델명 */
  carModel: string;
  /** 차량 종류 */
  carType: string;
  /** 차량 번호 */
  carNumber: string;
  /** 생성일 */
  createdAt: string;
}
