/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Allta API
 * Allta API 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */
import type { ReceiptCouponData } from './receiptCouponData';

/**
 * 응답 데이터
 * @nullable
 */
export type VerifyReceiptResponseData = ReceiptCouponData | null;
