/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Allta API
 * Allta API 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */

export interface VerifyReceiptRequest {
  /** 매장 전화번호 */
  storePhoneNumber: string;
  /** 승인 번호 */
  confirmNumber: string;
  /** 승인 날짜 */
  approvalDate: string;
  /** 결제 금액 */
  amount: number;
}
