/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Allta API
 * Allta API 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetBannerListResponse
} from '.././models';

import { customInstance } from '../../libs/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const bannerControllerGetBannerList = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetBannerListResponse>(
      {url: `/banner`, method: 'GET', signal
    },
      options);
    }
  

export const getBannerControllerGetBannerListQueryKey = () => {
    return [`/banner`] as const;
    }

    
export const getBannerControllerGetBannerListQueryOptions = <TData = Awaited<ReturnType<typeof bannerControllerGetBannerList>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof bannerControllerGetBannerList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getBannerControllerGetBannerListQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof bannerControllerGetBannerList>>> = ({ signal }) => bannerControllerGetBannerList(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof bannerControllerGetBannerList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type BannerControllerGetBannerListQueryResult = NonNullable<Awaited<ReturnType<typeof bannerControllerGetBannerList>>>
export type BannerControllerGetBannerListQueryError = unknown


export function useBannerControllerGetBannerList<TData = Awaited<ReturnType<typeof bannerControllerGetBannerList>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof bannerControllerGetBannerList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof bannerControllerGetBannerList>>,
          TError,
          Awaited<ReturnType<typeof bannerControllerGetBannerList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useBannerControllerGetBannerList<TData = Awaited<ReturnType<typeof bannerControllerGetBannerList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof bannerControllerGetBannerList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof bannerControllerGetBannerList>>,
          TError,
          Awaited<ReturnType<typeof bannerControllerGetBannerList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useBannerControllerGetBannerList<TData = Awaited<ReturnType<typeof bannerControllerGetBannerList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof bannerControllerGetBannerList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useBannerControllerGetBannerList<TData = Awaited<ReturnType<typeof bannerControllerGetBannerList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof bannerControllerGetBannerList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getBannerControllerGetBannerListQueryOptions(options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



